### ISSUE TITLE
[DTC/40v40] Re: The End Kingdom

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#10]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Re: The End Kingdom

## Gamemode & Map Description  
Theme: Something at the end

This is a 2-cores DTC  map that is a remake of [The End Kingdom](https://pvp.minecraft.jp/en/threads/4535), which I posted to Japan Minecraft PvP (JPMCPvP) 5 years ago and was rejected.
Players are divided into Crimson (Red) and Ender family (Purple), Everyone must leak lava from Small Core and Large Core on  enemy side.
The changes from original edition are as follows.

- Remade xml.

- Changed kits and team colors.

- Added another core for each team and renamed Small core, Large core.

- Removed the roof in the central hexagonal area.

- Remodeled base and observer spawn area.

- Added Defender tools chest in front of Large core

- Added trapped chest rigged with TNT. Players can get Diamond Tools and Deadly poison potion(trash).

- Added timelimit 60m

I'm glad I got the opportunity to post a remake map. :)

## Team Sizes
40 vs 40 (mega?)

## Screenshots
[Imgur](https://imgur.com/a/9kHFNL0)

# XML
[gist](https://gist.github.com/Pe241/a5b40efea267087c09ead8f0143360d8)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/90960647-1c7c4400-e4de-11ea-8936-f9f6e8d906b2.png)

# Download Link
[v1.0.0](https://drive.google.com/file/d/18FaV_q45sVGxceBj5ekLox5veRMo31tt/view?usp=sharing)

**Comment by fixitqixit** [comment]
Before this map gets up to its testing phase, I believe there are serveral cosmetic/physical features of the map that require updates. I enjoy the idea and layout of this map and i will outline below what I enjoy about this map and could be further extended upon (if possible). I will then follow up with a list of suggestions that I believe are required to combat the physical appearance and structure of the map in some parts.

**What I love:**
- Parts of the spawn base are really cool! Could require more detail in some parts but I like what youve got going.
- The islands that house the Large Cores are also quite attractive and I enjoy playing around them. I think they also need a few extra details in certain spots, but in general theyre pretty good. 
- The cores! I love how you have these two cores, not a lot of new maps use a similar idea with a front and back core. I believe this will make for more fun gameplay.
- Just a quick sidenote i love the little feather in the spawn kit which allows you to run faster. Good addition!
- Team sizes seem good!
- Ender crystals are also cool. Have you thought about adding more of them across the map? They might be quite fun to shoot and use to affect the opposing team.
- Nice obs spawn!

**What I think needs some improvements:**
- Some parts of the map are very bland and need more work done on them. The block palette of sandstone, quartz and endstone also clashes pretty badly and does not have much order to how its placed, which perhaps contributes to how the palette clashes with itself. [Astro by Chicky ](https://imgur.com/JIXmExz)uses a similar styled block palette to you which I think works pretty well. [Reshif's Wit's End](https://imgur.com/5BXEm6v) also uses endstone but has more patterns. I'm not sure if these examples help or not but I think they serve to illustrate my emphasis on improving the block palette.
- I would recommend not using glow-stone. Its texturing does not improve the block palette. I would recommend either using redstone lamps or getting rid of light sources and have night vision. Chicky also does this on [Astro](https://imgur.com/JIXmExz). As well as Reshif on Wits End.
- The sides of the lanes are [quite bland](https://imgur.com/a/cvbXD8v). I think they need a recurring pattern in order to improve how they look. I would recommend drawing upon the [Golden Drought series lanes](https://imgur.com/a/FSP5fBi). This repeated pattern is simple, yet very effective. 
- The top lanes of the map is incredibly thin (only two blocks). Im not sure if you intentionally did this to avoid tunneling, but  I think it should be the same thickness as the lower lanes of the map for both aesthetic gameplay reasons and for the physical appearance of the map. I also think the pillars that hold up this top part of the map need to be thicker. Currently, they are so thin they almost seem to lack any purpose and I think it takes away from the look youre trying to go for. 
- Theres some parts of the map that are quite abruptly shaped. As seen [here](https://imgur.com/a/mD31BwY). Sometimes this brutalist-styled way of designing map lanes works, and other times it doesnt. I feel like some of the diagonal parts of the lanes doesnt match up properly with overall layout and design of the map. I think there needs be either more boxy shapes across the map, or you need to make these diagonal lines more curvy so that the lanes have more flow. I know this may not make a lot of sense so I can elaborate if need be. 

I know when it comes to feedback it seems like I make a lot of _negative_ points about your map. The reason why I often go into so much detail is so that my message can get across and you actually have useful feedback to base your revisions off. I will say it again, I am very impressed with the effort you have put into all of the maps you have submitted. They show a lot of creativity and I think they will be very much enjoyed by players on this server. Looking forward to chatting with you soon!

**Comment by Pe241** [comment]
Thank you for your feedback @fixitqixit .
### Update to [v1.0.1](https://drive.google.com/file/d/1DIPZIzJ6_usSx-_lPFkm1Pd_eP0T-2vX/view?usp=sharing)
#### Change

- [Design](https://imgur.com/a/nZlUZ4T)

- Moved trap chest

- Added more crystals

- Removed stairs and added portals in hexagon area.

- Deleted all glowstone and added night vision

I can't think of any more ideas for design.
Organized the block pallet and used sandstone and team color stained clay to draw the line. I didn't use the proposed cobble stones, pistons, nether bricks, etc. because they would look messy if blocks with very different colors were used.
Honestly, I don't want to decorate any more because I want to cherish the contrast between the structure and the end's ground.
Regarding the shape of the terrain, I like the contrast between the shape of the center and the shape around the castle. (Especially hexagonal) I made some modifications, but I can't think of any more. 
The crystal issue sounds very interesting, but it can cause Team Griefing, so I'll just line it up on the obsidian tower for decorative purposes. When I play with this, I want to sniper the crystal on my side first. XD

I'm not very familiar with English, so I'm sorry for the unnatural sentences.
I really appreciate your great support.

**Comment by fixitqixit** [comment]
@Pe241 I just had a look around on the map and I like the changes you've made. While I still feel like theres room for improvement with how the map looks, the current changes you've made will suffice for the moment.

Also please dont apologise for your english, I can barely tell! I should be apologising for my ability to only speak english!

Once again good work with your map making! 👍

**Comment by fixitqixit** [comment]
Feedback:
- The large core is very difficult to attack due to how close it is to spawn
- It's not very clear that theres iron spawners in spawn, I barely saw any players get iron for themselves
- The front core is very easily rushed, it should be made harder to break somehow
- I still feel like large portions of this map are very bare and uninteresting to look at. Especially the area [surrounding the small core](https://imgur.com/a/s2U1dbr). In my opinion, more quartz structures should be made across the map to improve how it looks.
- The feather should be made 30% speed increase. Currently players are way too fast and its very difficult to play against them.
- A lot of people think the middle lanes are way too large and should either be made into two smaller lanes, or the size of the whole thing should be reduced

**Comment by master00ofdsiware** [comment]
The front core is too easy to attack, mainly because it is incredibly close to the mid island, and the structure around the core gives attackers a platform that they can easily bridge to. 

It's up to you how to make the front core harder to attack and easier to defend; some suggestions would be to modify the structure so that it doesn't cover the core, along with increasing the void gaps significantly.

**Comment by calcastor** [comment]
In hopes of garnering a wider range of player feedback on several pending yet 100% functional community maps, I've gone ahead and added many of them to the pools. This map has been included in that, and I hope to be able to collect at least the most prevalent feedback on the each map to post in their respective issues pages.

**Comment by calcastor** [comment]
Since my last comment I've removed this from the pools; it has potential with some bigger edits but I'm not thrilled with how it plays at present. It seems like the focus is only on the main core. I see that previously, the main core was very easy to attack and difficult to defend. I wouldn't say that's an issue now, however the core should only be one layer thick in any circumstance; the other changes you've made previously do more than enough to ensure that it's defendable. The side cores however feel like afterthoughts in a way, both in position within the map and when the map plays. It might be worth moving them up perhaps, or having them as monuments instead of cores.

Unfortunately I haven't seen much player feedback from when it was in the pools so but I'm hoping to solicit some in the discord server. Otherwise I'll try to provide more feedback later today.

**Comment by Pe241** [comment]
🏳
