### ISSUE TITLE
[Blitz: Spleef/64] Donut Spleef

### ISSUE THREAD

**Issue by Akinakumushi** [OvercastCommunity/CommunityMaps#100]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Donut Spleef

## Gamemode & Map Description  
This is a Arcade map like pikpikmerchant and Reshif's TNT Spleef 💣
I made this map to enrich the map pool of Overcast Comunity.

The brown stained clay around the field will be removed as soon as the game starts.

## Team Sizes
64 players in total

## Screenshots
https://imgur.com/gallery/ezr8Oma

# XML
https://gist.github.com/Akinakumushi/bfd7d3079e2b0fef77dbde5df78b164c

# Map Image
![map](https://user-images.githubusercontent.com/75409727/102768441-83decd80-43c4-11eb-96e5-6644c88265bc.png)

# Download Link
https://www.dropbox.com/s/oqcjtmx2gdw5kp8/Donut%20Spleef%20v1.0.0.zip?dl=0

**Comment by calcastor** [comment]
Quite a delayed response but this has been loaded to be tested at some point. I made a small XML edit which was decapitalising "spleefers" in the destroyable owner name in order to make it load.

**Comment by CrazyisCreeps** [comment]
Wow yea it's been a while since this was opened up. Uhhhh it has a couple issues, right off the bat it's a blitz map with one team, so it bugs out and ends as soon as a single player dies.

So I swapped it over to an FFA without realizing what the monument did. So now that outside ring never goes away. Maybe we remove it from the get go? Does it need to be there?

Second issue, your spawns are like 6 blocks in the air. So using the safe spawn attribute with this failed to generate spawns, and as such I disabled it to allow for spawning in the first place. Maybe lowering spawns would work better.

Lastly, there seems to be a couple of areas where players can stand on blocks that cannot be mined, such as the wooden pillars in the middle. This would need to be fixed.

**Comment by technodono** [comment]
this map has been in here forever and should probably be closed untill the author becomes active again

**Comment by CoWinkKeyDinkInc** [comment]
Since the map author is inactive, I have made a few changes in 69d5e55 to improve the quality of this map:
 - Replaced brown stained clay with Podzol, since monument modes with FFA is impossible at the moment, and it keeps the brown colour.
 - Made gravel a sticky block
 - Added snowballs to itemremove

All that is left is to fix the renenewables on the snow blocks (which I will get to soon) and development on this map should be generally finished.

**Comment by CoWinkKeyDinkInc** [comment]
# Version 1.0.3 f96138386180e9016a54ea1f21f3edf684163c2f

- Fixed the renewables
- Replaced gravel with mycelium since it seems that the falling blocks module doesn't stop them from falling
- Made diamond shovels Efficiency V
- Pruned the map again

The map is now in proper order, and it looks to me that this submission is finally complete.
