### ISSUE TITLE
[CTW/20v20v20v20v20] Ruediger's Pentawool

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#117]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Ruediger's Pentawool

## Gamemode & Map Description  
CTW

## Team Sizes
5 teams á 20

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map. Try to include at least one screenshot showing the entire map as a whole, from above, if possible.

# XML
dropbox

# Map Image
dropbox

# Download Link
https://www.dropbox.com/sh/iybj1ota7b1xeap/AACenSnynKtJzheq9bL-Qkaza?dl=0

**Comment by technodono** [comment]
you should make a imigur album for this map... it's free and is a way for people to quickly see the map

**Comment by CrazyisCreeps** [comment]
I'll be honest I was never a huge fan of this map, I found it was impossible to defend against and led to a lot of chaotic rushing. Since it's been a while since I last saw it played, I'm not against loading it up and seeing how it plays, but if it plays anything like I remember it, it may need some work before being considered for the pools.

**Comment by CrazyisCreeps** [comment]
Whoops my bad, I confused this with Octawool, I'm glad rockymine pointed that out haha! Sorry about that 😅

**Comment by CrazyisCreeps** [comment]
okay wait before I load this up, something needs to be done to make this more understandable for people to grasp. I spent 5 minutes running around the map until rockymine explained to me where the wools even were.

Secondly, why are teams pushing the other team's spawns to get to the wools? Any situation where you have to get someplace in such a close proximity as above the spawn never usually goes well.

**Comment by master00ofdsiware** [comment]
This was played earlier today. The map feels unfinished and it will need a lot of work before it can potentially be usable.
- Players were very confused about the map's layout; it is not indicated anywhere that the wool room is above spawn. Since the map's portal setup is unique, it would also help to have more indicators of where to go for the other team's sides; I think an example of a map that does it well is Tridente.
- Once you're actually in the "wool room" (although calling it as such is being generous), there is no way to hide from the enemy. You can't place blocks, and the enemy team can simply stand right outside the entrance on all 4 sides and shoot anyone in the wool room endlessly.
- The map's aesthetics are very bland, especially the large stained clay cuboids, along with the plain glass floors. In general, it feels like the map has very little attention to detail. Literally the most interesting parts of the map, aesthetically, are the wool monuments.
- How are teams supposed to defend a wool room with 4 entrances, over time? The layout seems like it will never play well, even if the rest of the map's issues are fixed.

**Comment by RuedigerLP** [comment]
Update 1.1.0:

- Subwoolrooms added for individual teams to be safe in the Woolroom. Subwoolrooms are small rooms inside the Woolroom that can only be entered by a single team, as signaled through colored blocks at the entrance. In this use they come with a chest that allows a team to store items in their Subwoolroom

- Woolrooms have only one entrance now, at the roof of spawn. To make defending possible while keeping the symmetry of the map, an entrance at the center of the roof was the only possibility. It's possible to build a defense wall around  the entrance, defense supplies come with the Spawnkit.

- A sophisticated Woolroom-Alert-System has been created, to direct player attention towards the Woolroom, using an ingame Alert message and audio visual effects, in this case timed firework rockets from a spawner, above the Woolroom entrance. Alerts happen after 5 seconds and then every 5 minutes. A centered Woolroom is at the core of this layout idea, therefore a more intuitive solution using the layout to make the position of the Woolroom more comprehensive for players is not apparent to me.

- Speed has been removed from the effects provided on your home island, strength, resistance and haste remain, these effects are a messure to balance the possible - 4:1 - attacker:defender ratio.

- Observer Spawn was added.

- Blocks in the Spawnkit, Woolkit and Killrewardkit have been reduced slightly.

**Comment by RuedigerLP** [comment]
https://github.com/OvercastCommunity/CommunityMaps/pull/133

**Comment by RuedigerLP** [comment]
#https://github.com/OvercastCommunity/CommunityMaps/pull/133

**Comment by RuedigerLP** [comment]
added in https://github.com/OvercastCommunity/CommunityMaps/commit/c80fe87cb5afe961036a85707754658bcc9f3ef9 (before but history is lost)
