### ISSUE TITLE
[KotH:Scorebox/24v24] Fishing Frenzy

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#172]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Fishing frenzy

## Gamemode & Map Description  
This map is a KotH with score-boxes...  I really wanted to make a map about fishing in PGM however I had to make it fun so I've included lure 8 rods in the kits and added score-boxes where you can redeem the fish you got for points. I'm hoping that having it as a side objective will make the map much more fun and still incorporate the fishing aspect... In addition I wanted the map to look like a shipping port so I did that

## Team Sizes
2 teams of 24 players

## Screenshots
https://imgur.com/a/oxQLiYt

# XML
https://gist.github.com/technodono/4a39fbb95f782f9bafc6208632905802

# Map Image
![map](https://user-images.githubusercontent.com/22761234/113474545-4bb75280-94bc-11eb-8515-af3e41d8535a.png)

# Download Link
[Fishing Frenzy.zip](https://github.com/OvercastCommunity/CommunityMaps/files/6252295/Fishing.Frenzy.zip)

**Comment by calcastor** [comment]
So I really like the concept of this map and the work you've put into the structures and aesthetic etc. of it. It's very fitting with the way you've tried to work fishing into the map's game play, which is something in Minecraft that I don't think I've seen implemented in a PGM map before, and I like that you've tried to do that.

However, I think this map needs some more changes before it's ready for rotation. The changes you've done most recently are heading in the right direction, especially given the confusion initially with it being a 3 point KOTH map. Right now though, I think it would play better as a Scorebox map in a similar way to how the map Miner Sixty Niner by Cazadorian and Vicei is. And while it's cool that you've tried to work in fishing, I can't help but think that it somewhat hinders game play. Players tend to avoid killing those who are fishing and those who are fishing don't tend to engage in combat, but it's also not something I want to see removed because I really think you could improve it in some way.

If you were to move this to being purely a Scorebox map, I think it might be worth modifying the kill reward in such a manner that you get a specific type of fish per each kill and rewarding a different amount of points for each type of fish upon scorebox entry, which also gives somewhat of an incentive to fish, at least in my mind. Right now I'm having a bit of trouble thinking of the best way to implement that XML side though, at least cleanly. I see right now that you've made fish worth more points compared to the emerald kill reward and that seems to also try to do what I described in the map's current state. You probably have a better idea of how you want to do that than I do.

Some player feedback regarding the score boxes: currently the region is set up in a manner that prevents being on the edge of your own score box in defending it (emerald block part before cobwebs). In some cases it seems that this can cause accidental boosting into the score box. Two specific suggestions mentioned were to either move the cobwebs forward one block, or make it so that you can stand on the emerald blocks when defending in so that it's more difficult to boost accidentally. Some further feedback from me: it might be worth modifying the score boxes to be wider, though not taller, if the map is moved to a Scorebox only game mode.

**Comment by master00ofdsiware** [comment]
If the map is to be kept in a similar state, fish need to be kept upon death. It is currently much too easy to spend a few minutes fishing and then die right in front of the scorebox, losing all the progress you made.

**Comment by technodono** [comment]
I think the score-points have to go... I'll bring back the fishing keep on death but you should still be able to pass them onto people. I am going to make the score-boxes wider and open up a lil more verticality on the map. so that mid isn't empty I think I'll add a spawner of some sort... But i need to know what's your thoughts on that

> 
> 
> If the map is to be kept in a similar state, fish need to be kept upon death. It is currently much too easy to spend a few minutes fishing and then die right in front of the scorebox, losing all the progress you made.

**Comment by calcastor** [comment]
> I think the score-points have to go... I'll bring back the fishing keep on death but you should still be able to pass them onto people. I am going to make the score-boxes wider and open up a lil more verticality on the map. so that mid isn't empty I think I'll add a spawner of some sort... But i need to know what's your thoughts on that
> 
> > If the map is to be kept in a similar state, fish need to be kept upon death. It is currently much too easy to spend a few minutes fishing and then die right in front of the scorebox, losing all the progress you made.

passing onto people is fine, just don't add them to itemremove and it should be good.

**Comment by technodono** [comment]
> them

yea defininitely... I'm working on an update to make that a thing... I think I'll figure out something for mid that meakes it more useful e.g. spawner but I still don't know what to replace the cp with

**Comment by technodono** [comment]
hmm... I think with the new changes this may eb pools ready btu IDK... feels more like a fun map than a real pools map

**Comment by technodono** [comment]
closing issue since i don't plan on fixing this map for a while. when I do I'll re-open it and update accordingly
