### ISSUE TITLE
[Blitz FFA/64] Shipwreck

### ISSUE THREAD

**Issue by CredensJustitiam** [OvercastCommunity/CommunityMaps#192]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [ ] The map has been tested locally to make sure it works

# Map Name
Shipwreck

## Gamemode & Map Description  
This is a blitz FFA map that takes place on a sinking ship. To be more accurate, the water rises every 5 seconds, and instantly kills people who touch it. The maximum time limit is 4 minutes. All players are given a fishing rod with Knockback 5, as well as 16 snowballs. Players are rewarded with 8 snowballs when they get a kill. Players are also incentivized to rush to the opposite side of the ship, as there is a chest that contains a one-use instakill sword.

## Team Sizes
The maximum amount of players should be 64.

## Screenshots
https://imgur.com/gallery/P3C65Na

# XML
https://gist.github.com/CredensJustitiam/ebb04719798e96be3c0ff46f65392b00

# Map Image
![map](https://user-images.githubusercontent.com/80809061/116322818-af5a3600-a771-11eb-8c19-075a8c05e224.png)

# Download Link
https://www.mediafire.com/file/tdcvueal9pzmaje/Shipwreck_%25281.8.9%2529.zip/file

-------
The creator for this map is LegoElfi, whose map I downloaded from [here](https://www.planetminecraft.com/project/rms-elfitania-sinking-final-plunge-30-minutes-after-the-explosion/). I altered the map in some places, such as adding many slabs for players to easily run up on the ship.

He gave me permission when I asked him about it on his YouTube channel.
![perm2](https://user-images.githubusercontent.com/80809061/116322907-d6b10300-a771-11eb-95b7-80a8713ff4d2.png)

**Comment by CredensJustitiam** [comment]
I believe the XML should work properly but it may need some adjustments.

**Comment by CrazyisCreeps** [comment]
I'll be honest, I'm not sure what's supposed to be happening here. I loaded it to mapdev, and I'm not sure I see any water rising or anything like that. How's this suppose to work?

**Comment by CredensJustitiam** [comment]
The idea for this map is that every 5 seconds the water should rise by one block, and the water region should be a death zone. I tried to accomplish this in my xml with some different sections:

1. The modes section defines different times at which to turn blocks into water.

2. The destroyables section uses the modes to turn different regions of the map into water after set amounts of time.

3. The regions section uses the modes in the same way to turn the same regions of the map into death zones at the same times as the water rises.

One of those sections must be the problem. Honestly I have no idea what part of it is wrong because I thought every part of this would work correctly, so I would appreciate your help with fixing this. My xml is really straightforward so this shouldn't take long.

**Comment by CrazyisCreeps** [comment]
I hate to put it like this, but I don't think it's worth the time trying to fix this. The map would require a lot of effort to get it working, with the end result being a king of the hill sort of map. It's a really interesting idea, and I love the enthusiasm for making maps like this, but I really don't think this one would work out.

Your monument regions are each 163,000 blocks a piece. There's no way they should be this big, they would need to be pruned down to a much smaller size. So that's adjusting just shy of 50 regions to smaller sizes. Say they get sized down to 7,000-8,000 blocks, that's a lot of blocks to be changing every 5 seconds, and I worry about the performance (how will the map handle? Will it cause lag?).

For the sake of learning btw, the way you tried to apply "death zones" isn't exactly how you'd need to go about it. Modes are only used for monuments/cores. You'd have to set rules with <apply/> that have specific time filters for each region one by one, so each rule is only triggered in each region once the correct amount of time has passed. This can be done with <time/> filters. So something like https://gist.github.com/CrazyisCreeps/79790eb7586114626cdaff730f009a56

You also want your cuboids to not have the same y level in the min and max. In order for your cuboids to work, the y in the max should be y+1 of the y in the min.

**Comment by CredensJustitiam** [comment]
It's fine if this doesn't work, I was worried about the performance anyway since so many blocks would be getting changed at once. We can stop working on this map then
