### ISSUE TITLE
[DTM/32v32] Beehive

### ISSUE THREAD

**Issue by Dowly06** [OvercastCommunity/CommunityMaps#195]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Beehive

## Gamemode & Map Description  
DTM, one front monument and one back monument for each time

## Team Sizes
32v32

## Screenshots
[Imgur](https://imgur.com/a/yWX8N7r) 

# XML
https://gist.github.com/Dowly06/3152457aafb19ede5515f454b1179027

# Map Image
![map](https://user-images.githubusercontent.com/84115754/118078174-95c90900-b383-11eb-8bb9-cffac3c43df0.png)

# Download Link
https://www.dropbox.com/sh/5rash8jq2w7mr34/AACa2v6AqRDjX-Gyrn4_DGA2a?dl=0

**Comment by calcastor** [comment]
Loaded with some changes:

1. I've NBT converted the map; seems it was a 1.12 world before. No issues with that thankfully!
2. I reorganized the XML a bit, mostly inconsequential stuff. Only behavioural change is that golden apples will not drop on death since they are a kill reward. However, plays are able to drop them between each other manually if needed. Also changed the proto version to 1.4.0, though there weren't any things in the XML that would have made it not work beforehand.

**Comment by calcastor** [comment]
Crazy found a copy of the map he had of the same version, however there were differences between the two XMLs for some reason. I've brought over what changes existed on Crazy's copy to what is loaded here as it seems it was a newer copy of the XML.

**Comment by calcastor** [comment]
Given that this has been previously play tested and in rotation on Stratus I've decided to see how it goes in rotation. If you ever have any changes you want to make in the future feel free to submit them in a pull request. Thanks again for submitting!
