### ISSUE TITLE
[CTF:TDM/25v25] Hellcave Fortress

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#20]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Hellcave Fortress

## Gamemode & Map Description  
Theme: Bone ghosts battle in the nether fortress

This is a score-game map. (1 kill=1 point,1 flag=10 points)
Players are divided into Wither Bones (dark red) and Gray Bones, and compete for scores.
Players can get emerald as kill rewards. Use to buy special weapons, armor, and effects!
Flag captured reward is emerald pickaxe. Use to dig an emerald block (=9 emeralds) in their base!
Players can get quartz in the central spawners room. (9 quartz= 1 emerald)
Match time is 14 min. After 7 minutes, gravel footings are fall down, lava leaks from the ceiling and blocks some passages.

## Team Sizes
25vs25

## Screenshots
[Imgur](https://imgur.com/a/jYbK7fI) 

# XML
[Gist](https://gist.github.com/Pe241/fbee615edb81c6efed055d5b3ae0751b)
# Map Image
![hFwLsbb17gNaER41599849338](https://user-images.githubusercontent.com/18105767/92962319-bd419c00-f4ab-11ea-8fcf-90a7fe0259e6.png)

# Download Link
[v1.0.0](https://drive.google.com/file/d/16r-rg7g794OP9NvHqfLFK23qwFbeClmy/view?usp=sharing)

**Comment by fixitqixit** [comment]
While I haven’t actually seen this map in game I feel like it again has a lack attentional to detail that some of your other maps have. Especially in areas like this (https://i.imgur.com/EONp5si_d.jpg?maxwidth=640&shape=thumb&fidelity=medium). 

If this map is meant to replicate the look of the nether, more natural terrain should be built, instead of straight likes and blocks corners. It really takes away from the appeal of the map. 

While it’s awesome that you’re building a ton of maps that all have their own unique gameplay and look, it’s important to spend time editing and refining parts of your map before you submit them. I can’t stress this enough. I recommend finishing the map, leaving it for a few days and then coming back to it to see if you can improve anything. That’s how I personally make maps (except I usually take way too long), and I think it seems to work reasonably well. 

I will take a closer look at the map when I’m next at my computer but I can’t guarantee when that will be, apologies! Anyway great work with churning out another map that I’m sure will be fun to play once it’s been adjusted and edited a bit more. 🙂 We really appreciate your hard work and contributions to this server.

**Comment by Pe241** [comment]
Retired this project.
