### ISSUE TITLE
[CTW/40v40] chle_

### ISSUE THREAD

**Issue by chleongithub** [OvercastCommunity/CommunityMaps#220]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

<img src="https://i.imgur.com/LC0aHbQ.png" alt="map" style="max-width:100%;">

# Map Name
chle_ (yeah, thats the name)

## Gamemode & Map Description  
This map does not have a void players have to bridge over. Instead I went fully experimental and made a huge wall players have to dig through in order to get to the other side. While in the wall, players are given night vision and haste 2. The rest of the map is just straight forward. Oh, and no, the large roof supported by the pillars is just there for decoration.

The woolroom however, I believe it has the largest interior of any woolroom in OCN history, so be sure to check out every corner of it!

I have absolutely no idea how this is gonna play lmao

## Team Sizes
Red vs. Blue 40v40

## Screenshots
[here u go](https://imgur.com/a/AYxPmV4)

# XML
[XML](https://gist.github.com/chleongithub/cd69c8b7545a7c7c054c59779b96c037)

# Map Image
<img src="https://i.imgur.com/9pZHhZL.png" alt="map" style="max-width:100%;">

# Download Link
[Download](https://www.dropbox.com/s/i89krl5fziz4bzu/chle_.zip?dl=0)

**Comment by Pugzy** [comment]
As a general convention, we do not allow maps that include usernames or 'special' characters.

Do you have an alternative name in mind?

**Comment by chleongithub** [comment]
> As a general convention, we do not allow maps that include usernames or 'special' characters.
> 
> Do you have an alternative name in mind?

Ah okay just take away the underscore then

**Comment by Pugzy** [comment]
Please come up with a more creative name.

**Comment by CoWinkKeyDinkInc** [comment]
This looks really nice, I could come up with a name for you if you want lol

**Comment by chleongithub** [comment]
> Please come up with a more creative name.

«chle map»

**Comment by Omote23** [comment]
Uhh.,, How about naming this map "Withdrawal of Deferred Retirement Income"?
Reason is...
1. digging is required instead of bridging. = which is a metaphor of Withdrawal from the big WALL
2. Big wall can be compared to Deferred Retirement Income, which is a Retirement income but it's on a pension account so that defers the retirement income tax.

**Comment by CrazyisCreeps** [comment]
https://randomwordgenerator.com/fake-word.php Pick the first one, easy peasy

**Comment by CoWinkKeyDinkInc** [comment]
Is this how you treat your friends? :( You need to move him back into the pen

![2021-07-29_20 43 56](https://user-images.githubusercontent.com/7586568/127591964-0699d14c-534f-463a-9d3e-e79c8cbca8d6.png)

**Comment by CoWinkKeyDinkInc** [comment]
Also this needs a quick spell check
```xml
<apply enter="only-blue" region="blue-spawn-dest" message="You may not enter the enemy teams spawn!"/>
<!-- fixed -->
<apply enter="only-blue" region="blue-spawn-dest" message="You may not enter the enemy team's spawn!"/>
```

**Comment by CoWinkKeyDinkInc** [comment]
Not sure if this was an oversight, but there are no extra building materials in the woolrooms, you should consider this since runners will probably be using blocks to plug in tunnels while they are running away. Your mobs can also be killed by players which if you don't want you can recreate them using the invulnerable attribute.

**Comment by chleongithub** [comment]
> Not sure if this was an oversight, but there are no extra building materials in the woolrooms, you should consider this since runners will probably be using blocks to plug in tunnels while they are running away. Your mobs can also be killed by players which if you don't want you can recreate them using the invulnerable attribute.

Maps have building blocks in their woolroom?

**Comment by Strangeys** [comment]
Wool room gear is way too OP. I would rather you stick to the standard of a power 1 bow, gapples, and a diamond piece of armor.
 - You should always avoid giving any weapon with KB/punch because it is very annoying getting knocked into the void by those. We've been removing them from public maps as much as possible. 
 - You should generally never give a sword that deals more damage than the normal one provided as it makes a straight up 1v1 very hard to lose when you already have gapples and armor. So please remove the enchanted swords and axes that have sharpness. 
  - Power 2 on bows is also ridiculous, power 1 is just fine.
  - I couldn't even find the diamond pickaxes for a long time. It's not clear where they are supposed to be.
  - Remove the poison splash potions, those are also another annoying thing to be on the receiving end of.
 
I'd recommend removing the kb 2 sticks in the defense chests otherwise it's almost an instant kill for anyone getting hit in a pit or above ground.

The spectating tunnels for the wool rooms are really cool, but casual players are going to have absolutely no clue about that and think this guy is just flying or doing some weird exploit. That tunnel should be encased in stained glass or something otherwise it's just another confusing thing for players to see happening.

The fact that the wall behind the cobwebs next to the wool is not bedrock is very weird because people are going to want to break that and be confused why as it's not clear where the woolroom region is at first glance.

You shouldn't put defense supplies right next to the point where people will make a wall and pit cause it will get in the way. You also don't need 3 double chests of supplies, you could move some of them in the spawns and leave one near by.

 You can mine your way to the ceiling by digging a staircase out of the 2x2 pillar that goes through each team's side. You might as well add bedrock up there instead of essentially letting players get up there and then only denying them access across mid or into the wool cause they'll just be disappointed or abused.
 
 You also use a region to deny digging up through mid when again you could just do the simple thing and put bedrock there so now people can just hit their head on a deny region which is just annoying.
 
 There's a power1,flame1,punch1 bow near mid. You should also get rid of that as well. 
 
 The victory monument is complex for no reason at all. You throw a jump pad into a portal which puts you into an area incased in barrier blocks which 1.8+ players see as invisible blocks and have to stick it into a very specific block that needs to be pointed out by a bunch of signs. By putting a jump pad there and denying access to it it also adds another annoying element for attackers to deal with because they may get hit into it.
 
 Efficiency 3 on the spawn pickaxe is too much, you already give haste 2 in mid and it's way too easy to break blocks for a defense with that much efficiency.

**Comment by chleongithub** [comment]
> Wool room gear is way too OP. I would rather you stick to the standard of a power 1 bow, gapples, and a diamond piece of armor.
> 
> * You should always avoid giving any weapon with KB/punch because it is very annoying getting knocked into the void by those. We've been removing them from public maps as much as possible.
> * You should generally never give a sword that deals more damage than the normal one provided as it makes a straight up 1v1 very hard to lose when you already have gapples and armor. So please remove the enchanted swords and axes that have sharpness.
> * Power 2 on bows is also ridiculous, power 1 is just fine.
> * I couldn't even find the diamond pickaxes for a long time. It's not clear where they are supposed to be.
> * Remove the poison splash potions, those are also another annoying thing to be on the receiving end of.
> 
> I'd recommend removing the kb 2 sticks in the defense chests otherwise it's almost an instant kill for anyone getting hit in a pit or above ground.
> 
> The spectating tunnels for the wool rooms are really cool, but casual players are going to have absolutely no clue about that and think this guy is just flying or doing some weird exploit. That tunnel should be encased in stained glass or something otherwise it's just another confusing thing for players to see happening.
> 
> The fact that the wall behind the cobwebs next to the wool is not bedrock is very weird because people are going to want to break that and be confused why as it's not clear where the woolroom region is at first glance.
> 
> You shouldn't put defense supplies right next to the point where people will make a wall and pit cause it will get in the way. You also don't need 3 double chests of supplies, you could move some of them in the spawns and leave one near by.
> 
> You can mine your way to the ceiling by digging a staircase out of the 2x2 pillar that goes through each team's side. You might as well add bedrock up there instead of essentially letting players get up there and then only denying them access across mid or into the wool cause they'll just be disappointed or abused.
> 
> You also use a region to deny digging up through mid when again you could just do the simple thing and put bedrock there so now people can just hit their head on a deny region which is just annoying.
> 
> There's a power1,flame1,punch1 bow near mid. You should also get rid of that as well.
> 
> The victory monument is complex for no reason at all. You throw a jump pad into a portal which puts you into an area incased in barrier blocks which 1.8+ players see as invisible blocks and have to stick it into a very specific block that needs to be pointed out by a bunch of signs. By putting a jump pad there and denying access to it it also adds another annoying element for attackers to deal with because they may get hit into it.
> 
> Efficiency 3 on the spawn pickaxe is too much, you already give haste 2 in mid and it's way too easy to break blocks for a defense with that much efficiency.

jesus christ

**Comment by calcastor** [comment]
With the conclusion of the contest and announcement of results we've begun to add a few of the contest maps, including this one, to the pools. Thank you for submitting!
