### ISSUE TITLE
[CTW/25v25v25v25] Old Life CTW

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/CommunityMaps#249]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Old Life CTW

## Gamemode & Map Description  
4-team 6 wools CTW, this it New Life CTW repurposed as a normal CTW

## Team Sizes
4 teams á 25

**Comment by calcastor** [comment]
last I tested this there were some small + inconsequential glitches xml side but it's definitely fit for pools otherwise. added in January 2022 pool update, hoping to double check the xml myself later unless anyone else does before me.

thanks for submitting, I'm glad this map is being used in a bit of a more conventional manner compared to the summer contest submission; while that was a very interesting concept it just didn't work out in testing due to player confusion that would have just been inherent to how it was as a map.
