### ISSUE TITLE
[CTW/DTM/20v20] Malupa

### ISSUE THREAD

**Issue by lunaceeee** [OvercastCommunity/CommunityMaps#268]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
What is the map called?

## Gamemode & Map Description  
CTW/DTM - break corresponding monuments to bridge via wool lanes.

## Team Sizes
20v20

## Screenshots
https://i.imgur.com/mZsnbem.png

# Map Image
https://i.imgur.com/N0RrsEq.png

# Download Link and XML
https://www.dropbox.com/s/5ptfism9mf414s5/Malupa.zip?dl=0

**Comment by Cazadorian** [comment]
[Album of map screenshots](https://imgur.com/a/DMlSHtK)

More details on how the map works:
The main objectives on this map for both teams are the wool rooms, with the monuments being optional monuments that unlock additional lanes for bridging when broken. In theory a team could win without breaking either monument, however this will mean having to push through a single lane that goes past the other team's spawn and so players will be incentivised to prioritise the monuments first despite them not being required.

**Comment by CoWinkKeyDinkInc** [comment]
Loaded in 1127455c7856234a0c4c30848fcad2d4da3a3f31

**Comment by lunaceeee** [comment]
[Malupa.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7148309/Malupa.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in bbbed5bc42da715eef8388aebeaef44b9577b8dc, which removes a dirt block in a wool monument.

**Comment by Cazadorian** [comment]
Map updated based upon feedback

- Removed the monuments from the sidebar to hopefully stop players mindlessly rushing them the second the match starts. This however does unfortunately mean no raindrops from breaking them, if a way of keeping raindrops while hiding the mons from the sidebar is ever implemented this should be updated.
- Denied bridging across all but the very centre of middle, this is to encourage use of the side islands as currently there is really no need to use them with how short the mid gap is
- Time set to 6000 due to Mame specifically complaining about it being night time

[Malupa V1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7585544/Malupa.V1.1.zip)

**Comment by technodono** [comment]
I myself haven't looked at the map but if the monuments keep getting pushed 1st round I especially don't think the change to hide monuments benefit the map at all... if you want to explore the idea maybe consider moving the monuments to slightly more defend-able pots or put focus onto one monument. O f course a match without defence should last ~5-7 min and those with 25+

I think if the monument then does become too hard to attack you can implement timed strategies that make the monument easier to mine over time or easier to get to. In general just with the way the monuments were placed from your image it looks like atm they are literally at mid and way too easy to push with the addition of having 2 monuments the defenders have to split their defences on. All that and the monuments do only give you a slight advantage. I think it needs to be used for something more so defenders we actually consider defending it instead of letting get really easily rushed.

**1 monument pls? DIfferent location so it's more challenging to get to, but gives that woolroom advatage**

Second this is about mid. maybe don't make it bridgeable at all...it looks like everyone would b-line it from spawn to the enemies side

**Comment by Cazadorian** [comment]
> I myself haven't played at the map but if the monuments keep getting pushed 1st round I especially don't think the change to hide monuments benefit the map at all... if you want to explore the idea maybe consider moving the monuments to slightly more defend-able pots or put focus onto one monument. O f course a match without defence should last ~5-7 min and those with 25+
> 
> I think if the monument then does become too hard to attack you can implement timed strategies that make the monument easier to mine over time or easier to get to. In general just with the way the monuments were placed from your image it looks like atm they are literally at mid and way too easy to push with the addition of having 2 monuments the defenders have to split their defences on. All that and the monuments do only give you a slight advantage. I think it needs to be used for something more so defenders we actually consider defending it instead of letting get really easily rushed.
> 
> **1 monument pls? DIfferent location so it's more challenging to get to, but gives that woolroom advatage**
> 
> _diff location: solves rushing More challenge: means more rewards_
> 
> Second this is about mid. maybe don't make it bridgeable at all...it looks like everyone would b-line it from spawn to the enemies side

I want the monuments to still be destroyed relatively early on, but from seeing the map play having them on the sidebar meant that people ignored the wools completely to just go for the monuments first in every situation, breaking them within like a minute of starting. I'm hoping this hiding+the middle change will result in them still being broken early but not completely tunnel visioned. 

At the moment I want to try keeping a small area in middle bridgeable to see how it plays, but if it still has issues I'm tempted to update the map to instead completely deny bridging over middle and place the monuments for both teams upon the small hills that are currently where you can bridge from.

**Comment by technodono** [comment]
> > I myself haven't played at the map but if the monuments keep getting pushed 1st round I especially don't think the change to hide monuments benefit the map at all... if you want to explore the idea maybe consider moving the monuments to slightly more defend-able pots or put focus onto one monument. O f course a match without defence should last ~5-7 min and those with 25+
> > I think if the monument then does become too hard to attack you can implement timed strategies that make the monument easier to mine over time or easier to get to. In general just with the way the monuments were placed from your image it looks like atm they are literally at mid and way too easy to push with the addition of having 2 monuments the defenders have to split their defences on. All that and the monuments do only give you a slight advantage. I think it needs to be used for something more so defenders we actually consider defending it instead of letting get really easily rushed.
> > **1 monument pls? DIfferent location so it's more challenging to get to, but gives that woolroom advatage**
> > _diff location: solves rushing More challenge: means more rewards_
> > Second this is about mid. maybe don't make it bridgeable at all...it looks like everyone would b-line it from spawn to the enemies side
> 
> I want the monuments to still be destroyed relatively early on, but from seeing the map play having them on the sidebar meant that people ignored the wools completely to just go for the monuments first in every situation, breaking them within like a minute of starting. I'm hoping this hiding+the middle change will result in them still being broken early but not completely tunnel visioned.
> 
> At the moment I want to try keeping a small area in middle bridgeable to see how it plays, but if it still has issues I'm tempted to update the map to instead completely deny bridging over middle and place the monuments for both teams upon the small hills that are currently where you can bridge from.

I can see where you are coming from but what I've been trying to explain is that the ammount of monuments and where they are place is a more likely contributor to rushing then hiding that feature and having some random player discover it

**Comment by Cazadorian** [comment]
> I can see where you are coming from but what I've been trying to explain is that the ammount of monuments and where they are place is a more likely contributor to rushing then hiding that feature and having some random player discover it

The monuments aren't something that's being hidden for some random player to discover, they're clearly visible and there's chat broadcasts to say what they are and what breaking them does. The issue at the moment is that people are treating them as an objective, rather than a utility. The point of removing them from the scorebox is to stop people viewing them as an actual objective as the wools are the only actual objective of the map.

**Comment by technodono** [comment]
> 

fair fair

**Comment by CoWinkKeyDinkInc** [comment]
> 

Loaded in a1033bd.

**Comment by CoWinkKeyDinkInc** [comment]
> Map updated based upon feedback
> 
>     * Removed the monuments from the sidebar to hopefully stop players mindlessly rushing them the second the match starts. This however does unfortunately mean no raindrops from breaking them, if a way of keeping raindrops while hiding the mons from the sidebar is ever implemented this should be updated.
> 
>     * Denied bridging across all but the very centre of middle, this is to encourage use of the side islands as currently there is really no need to use them with how short the mid gap is
> 
>     * Time set to 6000 due to Mame specifically complaining about it being night time
> 
> 
> [Malupa V1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7585544/Malupa.V1.1.zip)

Loaded in a1033bd.

**Comment by Cazadorian** [comment]
Large map update based on a recent playtest

- Completely denied bridging across middle
- Expanded the length of the side islands and middle void gap
- Unhid the monuments from the sidebar
- Reduced the number of monuments for both teams to just one each, located in the middle of their main islands
- Edited spawn and added resistance to the spawn kit as players were shooting from the wool rooms into spawn too much
- Minor map tweaks to better fit the new layout
- New map.png of the new layout

[Malupa V1.2.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7619969/Malupa.V1.2.zip)

**Comment by CoWinkKeyDinkInc** [comment]
Updated in f543a5c.

**Comment by Cazadorian** [comment]
Minor tweaks and bug fixes

- Emerald block added to item remove 
- Efficiency 1 added to the diamond picks to slightly speed up the speed of breaking monuments
- Renewables changed from rate to interval to stop the iron instantly respawning on the block you just broke
- Fixed spawn yaw being inverted

[Malupa V1.2.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7627894/Malupa.V1.2.1.zip)

**Comment by calcastor** [comment]
was added in February pool update but I think we'll swap it for Mo'ai for the month? forgot to close issue originally.
