### ISSUE TITLE
[DTC/10v10] Coreo

### ISSUE THREAD

**Issue by imroxas** [OvercastCommunity/CommunityMaps#297]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Coreo

## Gamemode & Map Description  
A Destroy the core map for nano-pool with a new concept feature. Players can get **oreos** in killrewards and by using two of it they can craft a **Haste II potion**. Also killrewards gives a short regeneration effect instead of golden apples.

The reason for the amount of cores is joking about the 10 cores Battlepass's mission (season 0).

## Team Sizes
10 vs 10

## Screenshots
[Imgur link](https://imgur.com/a/DXWxVVP)

# XML
[Coreo's XML](https://gist.github.com/imroxas/fdba52c7234b2aaf55d146156796638d)

# Map Image
![map](https://user-images.githubusercontent.com/69615091/140608230-c58aea16-d5d9-4110-950d-7302c6af6b57.png)

# Download Link
[Coreo v1.0.0](https://www.mediafire.com/file/tztii88z5wpasg2/Coreo.zip/file)

**Comment by CoWinkKeyDinkInc** [comment]
```xml
     <!-- === OBJECTIVES === -->
    <cuboid id="cookie-1" min="18,14,-9" max="25,17,-16"/>
    <cuboid id="cookie-2" min="18,15,-22" max="25,18,-29"/>
    <cuboid id="cookie-3" min="5,17,-22" max="12,20,-29"/>
    <cuboid id="cookie-4" min="-12,19,-22" max="-5,22,-29"/>
    <cuboid id="cream-1" min="-18,14,7" max="-25,17,14"/>
    <cuboid id="cream-2" min="-18,15,20" max="-25,18,27"/>
    <cuboid id="cream-3" min="-5,17,20" max="-12,20,27"/>
    <cuboid id="cream-4" min="12,19,20" max="5,22,27"/>
```
The Y axis of these regions do not completely cover the cores. `cookie-4` for example does not give credit to the player for breaking the obsidian directly underneath. `cookie-3` is also incorrectly defined so it credits a leak when it I leaked `cookie-2`, though this could be because the core regions are too large for their size. The core regions should cover all of the obsidian/lava and should not extend excessively beyond those regions. Efficiency might need to be reduced but we will see after testing. With efficiency II and haste II potion effects I do not think that we may need a stained clay mode. I think this could work as 12v12 right now. I have to say I really love the design of this map and the surprisingly unusual colour pattern.

**Comment by imroxas** [comment]
## Changes applied

- [X] Team sizes from 10v10 to 12v12.
- [X] All Y axis core regions lowered one block.
- [X] Cores `cookie-2` and `cream-2`  they have been moved. Check before/after [here](https://imgur.com/a/oibcs8o).
- [X] Clay mode removed.

Thanks @CoWinkKeyDinkInc for the suggestions!
Let's see how it works in fact.

### Downloads

[COREO v1.0.1](https://www.mediafire.com/file/y3egwx25f6vx3bq/Coreo_v1.0.1.zip/file)
[XML v1.0.1](https://gist.github.com/imroxas/d92f55f0b8beb1bc68b33735857bdf4b)

**Comment by CoWinkKeyDinkInc** [comment]
The core movement is a good choice, probably would reduce quick bridging and jumping onto the second core when the first one is being attacked. There's still core leaking issues. I got credit for leaking three cores when I only leaked one. Try remaking these regions, and adding comments for context (i.e. Core 1 is closest to spawn, Core 4 is furthest). You also missed a quartz block you used for worldedit so don't forget to remove that. Since the cores are circular you could try using the cylinder region which is easier to manage.

![2021-11-07_01 38 30](https://user-images.githubusercontent.com/7586568/140636649-997a4c20-686c-411d-9e66-4c800e56edcb.png)

**Comment by imroxas** [comment]
## Changes applied

- [X] Core sizes reduced.
- [X] Amount of cores reduced from 4 to 3 per team.
- [X] Locally tested. _Note: It is possible to get the 2nd coreo by making a "groove" to redirect the lava, but it is too tricky!!_
- [X] Ive added @CoWinkKeyDinkInc in the contributor lines.

### Downloads

[COREO v1.0.2](https://www.mediafire.com/file/skfkzqgtclrzcd2/Coreo_v1.0.2.zip/file)
[XML v1.0.2](https://gist.github.com/imroxas/2a5933bf9fdd97dc6c6d83f4ffe02013)

### Quick View
![image](https://user-images.githubusercontent.com/69615091/140638597-bb5d94df-d811-4dd1-966a-ed8fe683407f.png)

**Comment by imroxas** [comment]
# Coreo v1.1.0
## Changes applied:

- [X] Amount of cores reduced from 3 to 2 per team.
- [X] Respawn delay increased from `respawn delay="2.5s"` to `respawn delay="4s"`. (This is because one of the cores is very close to the spawn areas).
- [X] Locally tested.

### Downloads

[COREO v1.1.0](https://www.mediafire.com/file/ki3a6i865u8kzl6/Coreo+v1.1.zip/file)
[XML v1.1.0](https://gist.github.com/imroxas/617e01b5974499a42874e1387b21ab87)

### Core's change quick View
![image](https://user-images.githubusercontent.com/69615091/141752447-57de77a0-2c2c-4b6c-b5ae-a53b47609c9a.png)

**Comment by CoWinkKeyDinkInc** [comment]
Added in b2ed1a1.

**Comment by CoWinkKeyDinkInc** [comment]
After playtesting this map, the map has gotten rushed (there may have been a slightly higher player count. Try increasing the void gap and decreasing the height limit so that it is no higher than the obsidian on the highest coreo.

**Comment by calcastor** [comment]
the issues this map has aren't actually super detrimental imo, so I added it to the nano pool in a recent pool update. may suggest removing one of the cores but for now I'll close this issue.
