### ISSUE TITLE
[CTW/12v12] Patulog CTW

### ISSUE THREAD

**Issue by Cazadorian** [OvercastCommunity/CommunityMaps#328]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Patulog CTW

## Gamemode & Map Description  
This map is being submitted for the ongoing micro map making contest.

This map is mostly just a standard 3 lane CTW however instead of each team having two wools, instead each team has a wool room containing a dye spawner and a wool room containing white wool. In order to win a team must take both a white wool and a dye from both wool rooms and combine them together in order to get the wool they need for their victory monument. White wool is item cleared on death and each team has a different dye colour.

## Team Sizes
2 teams 12v12

## Screenshots
[Screenshots](https://imgur.com/a/qQCsGg2)

# XML
[XML](https://gist.github.com/Cazadorian/a94fe1fd27cb0b28911977511b7c35ee)

# Map Image
![map](https://user-images.githubusercontent.com/73002842/147375975-aea8444f-78a9-40b7-8f9c-dce6a1882b0b.png)

# Download Link
[Patulog CTW.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7819019/Patulog.CTW.zip)

**Comment by Strangeys** [comment]
I would highly suggest adding a pre-made defense in front of the wool room because having a 15 block wide lane be only 4 blocks long and then have a massively wide front line area in front of it, you're not going to see much use in attempting to defend when people are likely going to run it down the sides to avoid respawning players as much as possible. You'll probably need the wool room to be pushed back if you want them to defend better and add space for something like a bedrock wall with cobwebs.

**Comment by Cazadorian** [comment]
Map updated based on feedback with minor changes

- Icons added above each of the wool room to make their contents much clearer
- Changed map tip to alert
- Added a few missed blocks to the wool room's deny breaking filter

[Patulog CTW v1.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/7921257/Patulog.CTW.v1.1.zip)
