### ISSUE TITLE
[DTM/12v12] Pineium

### ISSUE THREAD

**Issue by DerStiv** [OvercastCommunity/CommunityMaps#338]
### Checklist
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Pineium

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.
Destroy the Monument. Pineium is small DTM Map which has the unique feature that you can get iron for armor etc. but only in the middle islands.

## Team Sizes
How many teams and how large are they?
12v12

## Screenshots
https://imgur.com/a/n8WOkAg

# XML
https://gist.github.com/DerStiv/3b369e08939ad755d500e3b7e71d6326

# Map Image
![Pineium 290x246 PNG](https://user-images.githubusercontent.com/96599295/147823915-84a96618-67fc-4a8f-a7dd-1772d2d6d9b1.png)

# Download Link
https://drive.google.com/file/d/1ldcXGPQyiHTnrkMBYlT2SwcVNeqyT6N-/view?usp=sharing

**Comment by KingOfSquares** [comment]
Opinion:

I think materials should always be identified by name and not id, since the id system is deprecated.
Im referring to line 101 in the XML:
```xml
<item>175</item>
```
175 should be switched with `DOUBLE_PLANT`/`double plant` as described in the reference material https://pgm.dev/docs/reference/items/inventory

In addition to the deprecation it's also easier to interpret the xml if names is used instead of numbers.
