### ISSUE TITLE
[DTM/20v20] Quintlet

### ISSUE THREAD

**Issue by IcedCode** [OvercastCommunity/CommunityMaps#357]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Quintlet

## Gamemode & Map Description  
5 monuments per team, destroy them all to win! Beacon monuments after 20 mins. 2 mons at front which'll be easier to get and rest set back further. Very different to most OCC maps so will play differently.

## Team Sizes
2 teams, 20v20

## Screenshots
https://imgur.com/a/sDzavNE

# XML
https://gist.github.com/IcedCode/f5d745b7973a6ad929d62ad4fe735425

# Map Image
![image](https://user-images.githubusercontent.com/7426927/149634647-a6ecc021-f23b-4b8e-a792-cde2683b4edb.png)

# Download Link
https://www.dropbox.com/s/axnnydkpch3jgzb/Quintlet.zip?dl=0

**Comment by Cazadorian** [comment]
I've removed this map from development phase to allow it to be sponsorable. This map has pretty fundamental issues with its layout, especially the back monument, and it would likely require pretty major changes to be suitable at all for the map pool. If you wish to make those changes you're welcome to reopen the issue, otherwise I'll close it for now.
