### ISSUE TITLE
[Arcade/60] Water Drop: Cacti Terror

### ISSUE THREAD

**Issue by mitchts** [OvercastCommunity/CommunityMaps#398]
### Checklist
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Water Drop: Cacti Terror

## Gamemode & Map Description  
Arcade, Water Drop, themed around Mega Cacti Terror (which in turn is based on Cacti Panic)

Thank

## Team Sizes
FFA, 60 players

## Screenshots
[Overview](https://mcresourcepile.github.io/pgm-maps/water_drop_cacti_terror/#/13/64/49/-1/world/world-smooth_lighting)

# XML
[XML](https://raw.githubusercontent.com/MCResourcePile/pgm-maps/master/maps/water_drop_cacti_terror/map.xml)

# Map Image

![map](https://github.com/MCResourcePile/pgm-maps/blob/32082fa0afd531382474889a0cd28c3233c2a9d4/maps/water_drop_cacti_terror/map.png?raw=true)

# Download Link
[ResourcePile](https://mcresourcepile.github.io/maps/pgm?dl=water_drop_cacti_terror)

**Comment by CoWinkKeyDinkInc** [comment]
Added in 1d7cfaf.

**Comment by CoWinkKeyDinkInc** [comment]
Restricting placing cacti at spawn and the first drop might be a great improvement.

**Comment by mitchts** [comment]
> Restricting placing cacti at spawn 

You can't place blocks at all in spawn - or at least not intentionally. Can you please clarify where exactly you mean?

**Comment by mitchts** [comment]
[Updated download via ResourcePile](https://mcresourcepile.github.io/maps/pgm?dl=water_drop_cacti_terror).

**Comment by CoWinkKeyDinkInc** [comment]
Updated in dfc856c.

**Comment by calcastor** [comment]
Thank you for submitting this map! It's become a regular for arcade events.

We made the following changes:

1. Added a 5 minute time limit
2. Made air renew over time so it doesn't become completely impossible to navigate the map when a lot of cacti are placed
3. Reduced the amount of cacti in the spawn kit

I'll close this issue for now but let us know if you'd like to make any further changes, whether related to our changes or just general changes. I personally haven't seen it play since we made the above changes so we may amend them based on gameplay.
