### ISSUE TITLE
[DTM/25v25] Maze Mountain Madness

### ISSUE THREAD

**Issue by mariogoaty** [OvercastCommunity/CommunityMaps#449]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X ] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X ] I have created an XML file
- [X ] I have created an map image
- [X ] I have uploaded the map zip file to a file sharing service
- [] The map has been tested locally to make sure it works

# Map Name
What is the map called?
Maze Mountain Madness

## Gamemode & Map Description  
What gamemode(s) do your map use? DTM / Arcade - You must try to destory your opponent's mountains

## Team Sizes
How many teams and how large are they?
25 v 25

## Screenshots
Create an album on [Imgur](https://imgur.com) with screenshots of the map.
![image](https://user-images.githubusercontent.com/97280598/182042895-80ea69f1-f850-40b7-88e2-4379587e1824.png)

# XML
Please [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-maps-xml-file) an `map.xml` file for your map and upload it to https://gist.github.com and link it here. - https://pastebin.com/mtLy4M5H

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box. - 
![image](https://user-images.githubusercontent.com/97280598/182042936-58f74d3f-9ea0-4d36-8b1b-7fd2cdcdcc10.png)

# Download Link
[Package the map](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#compressing-the-folder-to-a-zip-file) and upload it somewhere where we can download it, like **Google Drive** or **Dropbox**. - 
[mariogoat (14).zip](https://github.com/OvercastCommunity/CommunityMaps/files/9229627/mariogoat.14.zip)

**Comment by Cazadorian** [comment]
Feedback on this map after seeing it play:
- 25v25 is too big for this map, needs to be likely 12v12 at the max.
- Middle needs to be opened up more with more routes in and out of it, at the moment the map just turns into people bowspamming down the only corridor out of middle.
- The roof of the map should be made into black glass instead of black wool so observers can actually see what's going on easily.
-  The map might honestly play better if blitz is removed and a wooden pickaxe is added to the spawn kit, as at the moment the only purpose blitz really serves is to prevent the match lasting forever due to the above issues. If blitz is removed players will be able to join mid game and it may at some point be suitable for the map pool as well.

**Comment by mariogoaty** [comment]
thanks for the feedback and suggestions

**Comment by mariogoaty** [comment]
[maze_mountain_madness (1).zip](https://github.com/OvercastCommunity/CommunityMaps/files/9329835/maze_mountain_madness.1.zip)

Playercount;
etc

**Comment by CoWinkKeyDinkInc** [comment]
Updated in cb0b97bd92bafd90bb0beb71b211330b9d8a08c1

**Comment by Cazadorian** [comment]
After seeing the update play, the map likely still needs a few changes to be properly playable. 

- The only way into what is currently the endstone monument requires you to go through the enemy's spawn to reach, An additional path needs to be opened up.
- It is likely too quick to get to the quartz and prismarine monuments and the exits to them from spawn should be likely moved a bit to make getting to them slower or a longer respawn delay should be added.
- The monument materials need to be changed or a pickaxe of some form needs to be added. It takes 15 seconds to mine the endstone, 7.5 to mine the prismarine, and 4 to mine the quartz. I think the time for the quartz is fine, but the endstone and prismarine should be changed. The endstone mine time is currently so ridiculously high that even if you wipe out every single defender by the time you're halfway through mining it they will all have been able to return to the monument to stop you.

**Comment by mariogoaty** [comment]
thanks a lot with all the feedback however I haven't had the chance myself to play the map yet so I don't really have any knowledge yet :-)

**Comment by samschaap** [comment]
Hi, we have made some changes to the map based on the suggestions. The prismarine and end stone monument have been changed to (red) sandstone, the respawn timer has been increased to 3,5s and more paths to the monuments have been added. 
[maze_mountain_madness.zip](https://github.com/OvercastCommunity/CommunityMaps/files/9387827/maze_mountain_madness.zip)

**Comment by Cazadorian** [comment]
This issue has been inactive for about half a year and I'm not sure if the map itself will ever be fit for pools as the core concept of it makes it unlikely to ever properly fit even if it received further updates. I may consider putting this into the Funky Friday pool when I next update it as it could work in there as a quirky DTM, but otherwise it'll be left open for sponsoring and I'll close the issue for now.
