### ISSUE TITLE
[Spleef/12] Polar Spleef

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#478]
[### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [ ] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [ ] The map has been tested locally to make sure it works

# Map Name
Polar Spleef

## Gamemode & Map Description  
What gamemode(s) do your map use? Also provide a small description of the map and how you envision it playing.

## Team Sizes
How many teams and how large are they?

## Screenshots
In the map file

# XML

# Map Image
![map](https://user-images.githubusercontent.com/7586568/187536924-85b672bd-e581-4359-91d3-b993b494acf0.png)

# Download Link
https://www.dropbox.com/s/se5xwwl1dbfavns/polarspleef.rar?dl=0

**Comment by Cazadorian** [comment]
This map still has XML issues, and likely needs a lot of additional work to the map itself once those are fixed in order to bring it up to OCC's quality standards. As the map hasn't received any updates since being originally added, and the author has previously expressed desire to not update the map any further I'm closing this issue for now. If any further updates are made feel free to reopen the issue with them.

**Comment by oafMH** [comment]
https://gist.github.com/oafMH/2dc828912d8c971d9ea6449111510aab jacketjack fixed it guys here is the new xml
