### ISSUE TITLE
[KotH/15v15] Catre KotH

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#493]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Catre KotH

## Gamemode & Map Description  
KotH, small teams, a match length that isn't too long

## Team Sizes
15v15

## Screenshots
[Catre KotH on imgur](https://imgur.com/a/7FMG7oD)

# XML
[map.xml on gist.github](https://gist.github.com/Samuel-Roach/616a529e29e9aa039f2849a7ba0a04c5)

# Map Image
![make](https://i.imgur.com/ze3dr6S.png)

# Download Link
[Catre KotH on Mediafire](https://www.mediafire.com/file/8p15op9zjq5h0q3/Catre_KotH.zip/file)

**Comment by Cazadorian** [comment]
Feedback on the map after seeing it play:
- The map has a few out of bounds spots as a result of the vines, such as directly in front of spawn. It might be easier to remove the vines completely as they also might be annoying for fights even without the out of bounds spots.
- All of the iron trapdoors should be removed due to it being hard to bow down the hallways when right clicking just interacts with the trapdoor instead of your bow.
- I'm not sure why the map has decay on the control points, but it should likely be removed as I don't think it serves a purpose and the majority of KotH maps don't use it.
- The control points should have their capture region extend one block higher, as at the moment you're outside the region if you jump on the hill. 
- A lot of modern maps also use itemkeep+clear inventory for items such as golden apples instead of item remove, as it allows players to drop them to team mates but also have them not drop on death. I'd advise doing so on this map as well.

**Comment by Samuel-Roach** [comment]
Updated:

- I've removed the lowest vines that may cause issues, although I don't think that they're now low enough to affect gameplay.
- Iron trapdoors removed
- Just because most maps don't use decay doesn't mean it's a bad thing. If someone is solo capturing a point and they get knocked off with a bow, I don't think the point should instantly reset to the state it was before.
- Capture regions extended
- Updated to use itemkeep+clear for gaps and arrows

Other notes:
Added barrier blocks around the edge of a ledge near centre point to prevent players being knocked onto it.
gist has been updated and download link updated with latest version

**Comment by Cazadorian** [comment]
> * Just because most maps don't use decay doesn't mean it's a bad thing. If someone is solo capturing a point and they get knocked off with a bow, I don't think the point should instantly reset to the state it was before.

The normal solution to this is simply to use incremental="true", which doesn't have any kind of decay or recovery so if a player leaves a hill mid capture that progress is kept until an enemy player reverses it or that team finishes capturing the hill.

**Comment by Samuel-Roach** [comment]
> > * Just because most maps don't use decay doesn't mean it's a bad thing. If someone is solo capturing a point and they get knocked off with a bow, I don't think the point should instantly reset to the state it was before.
> 
> The normal solution to this is simply to use incremental="true", which doesn't have any kind of decay or recovery so if a player leaves a hill mid capture that progress is kept until an enemy player reverses it or that team finishes capturing the hill.

Ahh true, I must've missed it in the docs. Gist and download updated.

**Comment by Samuel-Roach** [comment]
[Download](https://www.mediafire.com/file/fyeqmatzdnmv3kx/Catre_KotH.zip/file)

v1.0.4
Shortened rotation from side hills to mid

**Comment by calcastor** [comment]
The download for this is inactive; I think I was able to get it from mapmaker though.

I'll try this in pools and feedback can be actioned internally, closing for now.
