### ISSUE TITLE
[CTW/32v32] Mine Your Own Business

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastCommunity/CommunityMaps#5]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Mine Your Own Business

## Gamemode & Map Description  
This is a CTW map, where the lanes and wool rooms are inside a large mountain, themed after a mine. There is a small burned town on an island which serves as the middle area between the two teams. Each team defends two wools, and the wool lanes are symmetrical inside the mountain. There is a main set of tunnels linking spawn to the iron area and the map's center, and additional small tunnels from spawn to the wool lanes. Finally, movement is permitted on the outside of the mountain at ground level, and from this area there are two "shortcut" tunnels leading into the mountain. The mountain has several hidden areas and passages, one of which leads to a cabin at the mountain's summit.

Since the wool lanes are enclosed, unlike on most CTW maps, some changes may be required to balance the map and prevent it from being too easy to rush or too easy to stalemate. This would be evident from gameplay testing.

## Team Sizes
There are two teams, 32 players each.

## Screenshots
Ignore the naturally generated world around the map's exterior. That is not present in the download.
https://imgur.com/a/zHvYOOX

# XML
Included in the zip.

# Map Image
Included in the zip.

# Download Link
[Mine Your Own Business.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5067284/Mine.Your.Own.Business.zip)

**Comment by TheMolkaPL** [comment]
Please change world type to flat, so that they sky is blue, not dark gray. You can do that with [NBTEditor](https://dev.bukkit.org/projects/nbteditor) by editing `level.dat` file of your world.

**Comment by profbananaslug** [comment]
i was partially responsible for this map and i sincerely apologize

**Comment by master00ofdsiware** [comment]
The download in the original post has been updated with several changes and fixes, including changing the world type to flat.

**Comment by fixitqixit** [comment]
At first I was really confused how this map functioned when testing it out in game. However, I've grown to actually quite admire the idea behind this map as well as certain areas of the map. I think this map has a lot of potential and is a concept I've never really seen before on an Overcast (Network or Community) map. I'm going to jot down some suggestions for the things I think should be changed and things that don't need to be changed/could be further capitalised on.

**Pros:**

- The tunnel/lane system that has been introduced is really cool. I believe this will be both fun to play and defend in.
- The block palette and style of the mines are quite cool, I enjoy running through them and most of them are wide and tall enough to manoeuvre through.
-  The current layout of the map looks like it will function as intended.

**Things that could be improved:**

- While I enjoy many of the parts of the map that have been built, I've often got the impression that the map was either rushed or parts of the map needed more building attention were neglected. While I understand the theme of the map with the large mountains, they kind of look a bit odd and quite unnatural (due to the visible use of worldedit). If they looked more like the [mountains on Moonlight Summit](https://imgur.com/a/G7dxZVI), for example, which have had considerable effort put into making them visually and functionally appealing, I would enjoy looking at this map a lot more. Considering much of the top half the mountain has no internal use (whether through mines, or any other lane/other use), I feel like the size of the mountain could be reduced significantly. I believe this would make the map more visually pleasing. Another alternative option would be to turn the whole map into a valley. Perhaps this could be like Monument Valley in a way with how both sides of the map are [connected](https://imgur.com/a/z4ynvOa).
- While certain parts of the map have a lot of detail, others are seriously lacking. Personally I feel like more trees should be used to make the mountain more attractive. This could be done through either custom trees or regular trees. If you would like custom trees you could ask map makers like rockymine, or maybe even myself for trees you could simply copy paste into the map. Parts of the mines too are very rigid in how they've been carved out of the mountain. The very rectangular designs of the larger mines gives the impression that they are very unnatural. This is also a pretty easy fix by just adding some stone around the sides and tops of the cave.

- Another really big thing is the lack of mines!! I feel like this idea for the lanes is so excellent but so much of the map fails to capitalise on using more of them. I feel like there could be so many more mines that interconnect and tangle around each other, making for even more exciting and creative gameplay. The mine shafts do this excellently, and I think both more of them and perhaps more larger mine shafts should be implemented.

**Other Suggestions:**

- The spawn point for obs spawn should be made .1 or .2 blocks higher. I'm unsure if its due to either my version of minecraft (1.5) or my slower connection to the server, but I will often glitch through the block. Also, while I like the idea of having the obs spawn there, new players to the server (or even players familiar with pgm maps) who are unaware of the ability to be teleported out of the spawn may be very confused as to where they are or what map they are playing initially. 
- I think the empty parts of the mountain should be filled in. If a player right clicks the compass to pass through the mountain they should be teleported to an actual part of the map, not a meaningless dark void. It also makes me again think part of this map is unfinished and still needs more work done on it.


I know that parts of this feedback may come across as negative due to how much I've said about things I'd like to see changed, but I still believe this map has a lot of potential and could be really fun to play. I believe it just needs to be polished up a bit more and some larger changes made to how much of it has been built. I'm willing to provide more feedback or better articulate certain parts of what I've written, if needed.

**Comment by master00ofdsiware** [comment]
Thanks for looking at the map, and for the detailed feedback.

> While certain parts of the map have a lot of detail, others are seriously lacking. Personally I feel like more trees should be used to make the mountain more attractive. This could be done through either custom trees or regular trees. If you would like custom trees you could ask map makers like rockymine, or maybe even myself for trees you could simply copy paste into the map. Parts of the mines too are very rigid in how they've been carved out of the mountain. The very rectangular designs of the larger mines gives the impression that they are very unnatural. This is also a pretty easy fix by just adding some stone around the sides and tops of the cave.

That's fair. I will add more trees to the mountain, and make the mine edges less rectangular. Specifically for the mountain's exterior, I will see if there are other things I can add to make it look more lively.

> While I understand the theme of the map with the large mountains, they kind of look a bit odd and quite unnatural (due to the visible use of worldedit). If they looked more like the [mountains on Moonlight Summit](https://imgur.com/a/G7dxZVI), for example, which have had considerable effort put into making them visually and functionally appealing, I would enjoy looking at this map a lot more. 

How do you think the use of worldedit is visible on the mountain? I will see if I can try and make it look more natural, but I'm not really sure of when and how; it also doesn't really affect gameplay.

I also think that once the mountains are more detailed (trees, etc.), the shape being unnatural will become less visible.
> Another really big thing is the lack of mines!! I feel like this idea for the lanes is so excellent but so much of the map fails to capitalise on using more of them. I feel like there could be so many more mines that interconnect and tangle around each other, making for even more exciting and creative gameplay. The mine shafts do this excellently, and I think both more of them and perhaps more larger mine shafts should be implemented.

I have ideas for where more tunnels could go, but I didn't want to add too many before I see how the map plays with its current layout. I'd prefer to get a better sense of where players go on the map before deciding where to create new mineshafts.
> The spawn point for obs spawn should be made .1 or .2 blocks higher. I'm unsure if its due to either my version of minecraft (1.5) or my slower connection to the server, but I will often glitch through the block. Also, while I like the idea of having the obs spawn there, new players to the server (or even players familiar with pgm maps) who are unaware of the ability to be teleported out of the spawn may be very confused as to where they are or what map they are playing initially.

Thanks for letting me know about this. I will create a new observer spawn elsewhere on the map, to avoid the risk of players falling into the void when spawning.
> I think the empty parts of the mountain should be filled in. If a player right clicks the compass to pass through the mountain they should be teleported to an actual part of the map, not a meaningless dark void. It also makes me again think part of this map is unfinished and still needs more work done on it.

The map's interior being hollow allows for the layout to be more easily visualized, which helps with planning possible new tunnels or modifications of the existing layout. I will fill the mountain with stone when the layout is more or less finalized, but for the time being I'll give observers night vision so they can find their way out more easily.

**Comment by master00ofdsiware** [comment]
I have updated the download in the original post with the latest version of the map.

Here is a summary of the changes, which are based on the feedback given above.

- There is a new observer spawn in a different location, to prevent players from falling into the void when spawning.
- Observers are given night vision; if they find themselves inside the mountain, they can now navigate more easily.
- The mountain now has more mine tunnels at various levels; one of them contains diamonds, the other emeralds. These tunnels are connected to the other mines by an assortment of internal passageways. To accommodate for the addition of diamonds, the armor in the spawnkit has been upgraded. 
- The previously mentioned tunnels have entrances on the mountain's exterior, and paths wind from the bottom of the map up to these entrances via the mountainside.
- Sharply contoured tunnel edges have had extra material added, so that they look more natural.
- I have attempted to make the mountain's exterior look better. This includes making the block palette a bit more varied, and adding more trees. These aren't massive changes, but when combined with the wooden paths to the mine entrances, I believe the mountain is definitely more interesting to look at now, compared to before.

**Comment by CoWinkKeyDinkInc** [comment]
> Please change world type to flat, so that they sky is blue, not dark gray.

I didn't realize that was the problem in my Q*Boid map lol, a year ago I wasted my time moving all the regions up by 64 blocks lol

**Comment by master00ofdsiware** [comment]
I have submitted the new version of this map in a PR: https://github.com/OvercastCommunity/CommunityMaps/pull/12

**Comment by fixitqixit** [comment]
`<renewables>
    
    <renewable interval="1800" grow="true" avoid-entities="false" particles="true" sound="true">
        <region>
            <rectangle min="oo,oo" max="-oo,-oo"/>
        </region>
        <renew-filter>
            <any>
                <material>air</material>
            </any>
        </renew-filter>
        <replace-filter>
            <any>
                <material>air</material>
                <material>stained glass</material>
            </any>
        </replace-filter>
    </renewable> 
<renewables>`

**Comment by fixitqixit** [comment]
Sorry posting this on my phone and only just saw your message about the renewable. The following Snippet is kinda broken in a way... the version of PGM occ uses appears to have some bugs associated with the renewables module (maybe?) hence why the `interval` appears to be listed for so long.

**Comment by fixitqixit** [comment]
I also paired this with the falling blocks module which means blocks that are removed underneath will allow blocks on top to fall neatly in line with other blocks

**Comment by master00ofdsiware** [comment]
I'll experiment with the disappearing blocks on my end, but I'm still not sure of whether I'll implement them. For the time being, the changes in the PR should be sufficient for further testing.

**Comment by CoWinkKeyDinkInc** [comment]
I just set this map for a brief moment, and it seems many players don't like it. I think dentmaged said that this map went from a full map and half of the players left the server. For me personally I found the map confusing to find armour, and there was a filter that needs to be adjusted as I couldn't remove the enemy wool from the mid island. It's something to prevent the breakage of signs.

**Comment by CoWinkKeyDinkInc** [comment]
Looks like progress on this map is complete, and it won't be added to the pools anytime soon. Thanks for the contribution! :)
