### ISSUE TITLE
[hns/53] Hide n' Seek: Polus

### ISSUE THREAD

**Issue by alejo112** [OvercastCommunity/CommunityMaps#519]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
 Hide n' Seek: Polus

## Gamemode & Map Description  
Hide and seek

## Team Sizes
50 and 3

## Screenshots
https://imgur.com/a/OyWROSF https://imgur.com/a/kgFOkIc

# XML
https://gist.github.com/alejo112/5ccb26087107df95372d1a90c3881d66

# Map Image
![map](https://user-images.githubusercontent.com/79621801/194744573-6a59fefd-f93e-4302-99c8-7272d6e18b38.png)

# Download Link
https://www.mediafire.com/file/izo5h5m8wnddud9/polus_hns.zip/file

**Comment by CrazyisCreeps** [comment]
Damn nice screenshots!

**Comment by CrazyisCreeps** [comment]
Loaded in https://github.com/OvercastCommunity/CommunityMaps/commit/0a0cde4f13d37111c03c87fb2f0eeb90ace7c651

**Comment by Cazadorian** [comment]
We have phased out Hide n' Seek in favour of infection due to the format allowing players to join mid match, and so we are no longer accepting new Hide n' Seek maps and have unloaded all existing ones that have an infection variant. As this map has an infection variant in the works it has also been unloaded, but once the infection variant is finalised please make a new replacement subnission.
