### ISSUE TITLE
[CTW/24v24] Apostle

### ISSUE THREAD

**Issue by Samuel-Roach** [OvercastCommunity/CommunityMaps#539]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Apostle

## Gamemode & Map Description  
2 team CTW

## Team Sizes
24v24

## Screenshots
[Images](https://imgur.com/a/u8eCTS2)

# XML
[XML](https://gist.github.com/Samuel-Roach/089a989ed8dfab2b7435d8cd4e099e50)

# Map Image
![map.png](https://imgur.com/yqEiDL1.jpg)

# Download Link
[Download](https://www.mediafire.com/file/61j2a7f2yjy68kn/Apostle.zip/file)

**Comment by calcastor** [comment]
Loaded in 483d2cbabd10ad9e5f9194f7803bfb51d5d3782c with the following changes:

- Unbreakable default armour
- Planks instead of logs (2 stacks, we have largely moved away from having logs in spawn kits)
- Block kill reward (16 planks, 8 stained clay at the moment)
- Swapped to itemkeep rather than itemremove for a lot of kit stuff. This prevents losing an item if you accidentally drop it, but won't keep it around after death.
- Related to above, block-drops module so placed planks and stained clay don't drop when broken
- Added toolrepair for kit tools (itemkeep currently won't apply if a player logs out, so repair kit tools in this instance)

**Comment by Samuel-Roach** [comment]
## Version 1.0.2 - [Download link](https://www.mediafire.com/file/afvuczvvn9aa891/Apostle.zip/file)
### **Changelog**
- Renamed Sword and Bow in chests to Power Bow and Sharpness Sword
- Added infinity to Power Bow
- Increase wool-room sizes

**Comment by Cazadorian** [comment]
> 



> ## Version 1.0.2 - [Download link](https://www.mediafire.com/file/afvuczvvn9aa891/Apostle.zip/file)
> ### **Changelog**
> * Renamed Sword and Bow in chests to Power Bow and Sharpness Sword
> * Added infinity to Power Bow
> * Increase wool-room sizes

Updated in 7534275

**Comment by Cazadorian** [comment]
This map has been in the pool for the past month without any major issues arising, so I'm closing this issue as complete for now. Thank you for the submission.
