### ISSUE TITLE
[Shave/16vs16] Sheer Heart Attack

### ISSUE THREAD

**Issue by JosueSaenzLacayo-UCR** [OvercastCommunity/CommunityMaps#549]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Sheer Heart Attack

## Gamemode & Map Description  
Shave or destroy-the-monument game mode

## Team Sizes
20vs20

## Screenshots
[Imgur](https://imgur.com/gallery/d1faBXx) 

# XML
[GIT](https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/137c04e866432238d5b3cfddcf64fb967394bb48/SheerHeartAttack.xml) 

# Map Image
![2023-02-20_20 34 27](https://user-images.githubusercontent.com/82010545/220236844-bc0ae1af-e2da-4a11-84d9-aee6ff259198.png)

# Download Link
[Package the map](https://www.dropbox.com/s/nw13e50gtcmdgwi/Shave_%20Sheer%20Heart%20Attack.zip?dl=0)  **Dropbox**

**Comment by technodono** [comment]
The premise of the map looks good but the builds don’t quite seem up to scratch with some of the more modern submissions. I might suggest that you try make everything more curved (heart, anchor eye hole) and also try to mix the wool with more blocks (I do understand you want the whole map shaveable).

**Comment by JosueSaenzLacayo-UCR** [comment]
Thank you for your recommendations, they are well received. If I make changes to the map in the future, I'll keep them in mind.

**Comment by Cazadorian** [comment]
Initial feedback on the map:
- I would likely completely remove the drop tube from this map as it being directly in front of the monument will block skybridges and a lot of arrows fired towards the monument. The map likely doesn't need it and it can be replaced with a different spawn.
- The frontlines at the moment feel very cluttered with the amount of purple wool, this likely needs to be modified in some way. I'd either reduce the amount of the purple wool structures, or completely replace them with different structures that take up less space on the frontlines.
- I would move or remove the blue glass sphere in the middle of the map as it will likely confuse players as to where they can and can't build, due to being unable to build upon it but being able to get to it.
- There's a few XML changes that likely should be made, such as adding unbreaking="true" to all of the tools, or disabling repairing of monuments due to red team being able to repair it with the wool and glass in their spawn kit.
-  I would also likely update the shape of the map itself to be less rectangular, similar to what Technodono mentioned but including the layout of the map as well.

**Comment by JosueSaenzLacayo-UCR** [comment]
I redid the map taking into account all the comments, thanks!. I changed everything in the original submission.

**Comment by technodono** [comment]
A lot of the aesthetics look better, it's not perfect but I'm pleased with the improvements :)

**Comment by JosueSaenzLacayo-UCR** [comment]
Hello!. After this map has been tested, mapdev recommends removing the glass around the heart, then doing that and changing the XML (a bit), here are the links 
map zip already prune : https://www.dropbox.com/s/p5a59rn50rf8z7y/Shave_%20Sheer%20Heart%20Attack.zip?dl=0
XML: https://github.com/JosueSaenzLacayo-UCR/XML_Maps_OvercastCommunity/blob/99ddc4038edba8b0922bbed8441d76500b8c7ad1/SheerHeartAttack.xml
