### ISSUE TITLE
[FFB/8v8] Flag Football: NYC

### ISSUE THREAD

**Issue by samschaap** [OvercastCommunity/CommunityMaps#557]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Flag Football: NYC

### Gamemode & Map Description

Flag Football map, with a city theme

### Team Sizes

2 teams, 8v8

### Screenshots

https://imgur.com/a/p8nUzGT

### XML

https://gist.github.com/samschaap/45df2466666c29efd69be09b196eaf1a

### Map Image

![map](https://user-images.githubusercontent.com/1810738/202868579-7b1c6030-ae81-4c19-a59a-b15565149337.png)

### Map Download

[flag_football_nyc.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10047843/flag_football_nyc.zip)

**Comment by Cazadorian** [comment]
The main initial feedback Mame and I have with this map is that the playable space at the moment is likely too thin, and the soul sand at the end is too punishing to have. The map would greatly benefit from having the playable lane widened by a few blocks, and potentially some of the smaller islands slightly merged together. 

As for the soul sand another Flag Football map, Waffle House, has a very similar layout for the stairs up to the net but with regular blocks instead of soul sand. On that map defending from on top of the other team's net is already incredibly strong, and having those blocks be soul sand instead would make capping ridiculously hard if someone tried to defend from there. I would likely just swap this soul sand out for regular blocks instead.

**Comment by samschaap** [comment]
Thanks for the feedback and suggestions, we will make some changes to the map

**Comment by oafMH** [comment]
check now is goodw i think

**Comment by samschaap** [comment]
We made changes to the map, the map is now wider and the flag island and other small islands have been expanded/merged. The stairs have been changed from soul sand to stone bricks with some stair and slab blocks to make going up to the net easier. 
XML and download are the updated version.

**Comment by samschaap** [comment]
XML has been updated to 1.0.3 to fix a bug where the flag would not capture when a player did not move after being teleported.
https://gist.github.com/samschaap/45df2466666c29efd69be09b196eaf1a

**Comment by calcastor** [comment]
This plays pretty well IMO and was in pools as one of two Flag-Football-Maps-in-Residence until it was cycled out for this month's update. Given that it is in a such a usable state I will close this issue. Thank you for submitting!
