### ISSUE TITLE
[DTM/8v8] Deadly Gaze

### ISSUE THREAD

**Issue by Flamiix** [OvercastCommunity/CommunityMaps#564]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Deadly Gaze

### Gamemode & Map Description

DTM
-2 monuments of gold per team

### Team Sizes

8v8

### Screenshots

https://imgur.com/a/iL3VHEe

### XML

https://github.com/zzuf-fer/zzuf/blob/main/deadly_gaze/map.xml

### Map Image

![2022-11-12_21 20 10](https://user-images.githubusercontent.com/105971633/201493057-eb18b5c9-a1d7-448d-9781-e4fdc11af870.png)

### Map Download

https://cdn.discordapp.com/attachments/1032799877454901258/1042118491228082196/deadly_gaze.zip

**Comment by Cazadorian** [comment]
Initial feedback on the map:

- The map currently isn't mirrored, and middle has a lot of differences on each team's side including one side having a large tree that is absent on the other team's side. Ensure that for a map like this that you mirror the map properly.
- I would adjust the spawn so players spawn facing the staircase, rather than having to turn immediately after spawning to run up it as this will likely become annoying very quickly upon respawning.
- Is this map intended to be an 8v8, or a 16v16? The title of this submission claims 8v8, but the map's XML has it set as a 16v16.
- The wood, glass, and golden apples in the spawn kit should likely be added to itemkeep to avoid them dropping on death and cluttering up inventories. Tool repair should also be corrected from iron pickaxe to stone pickaxe.
- The tools in the defending supplies chest in spawn are currently worse than the tools in the actual spawnkit, these should be adjusted to be better or removed due to being redundant.
- Initially it seems that not being able to break any of the existing blocks around the monument may prove to be awkward when played, but I would have to see the map play first before making any judgement calls on that.
- As the map is dark with little lighting, it'd likely benefit from having night vision added to the spawn kit for players who don't use full bright.

**Comment by mariogoaty** [comment]
Thank you for the feedback - we've changed everything 

Flamiix update coming soon

**Comment by Flamiix** [comment]
The map must be updated now, same for XML and description.

**Comment by Cazadorian** [comment]
Map has been in the pool for a few months and seems fine, so closing this issue for now. Thanks for the submission.
