### ISSUE TITLE
[MIXED AD/24v24] Castle Assault

### ISSUE THREAD

**Issue by EpicPuppy613** [OvercastCommunity/CommunityMaps#598]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Castle Assault

### Gamemode & Map Description

- Attack/Defense
- PL
- DtM
- CP

The map is played in 3 stages:
1. Bring the TNT (payload) to the wall
2. Blow up the middle segment of the wall
3. Capture the castle courtyard

### Team Sizes

2 teams: Attackers and Defenders, both with 24 players

### Screenshots

https://github.com/EpicPuppy613/maps/blob/main/Castle%20Assault.md

### XML

https://gist.github.com/EpicPuppy613/27d08c7d3febd35f43e9a7ee7bfc7d71

### Map Image

![map](https://user-images.githubusercontent.com/61771471/210122315-633ad621-961f-46a2-a334-7c9220290f62.png)

### Map Download

https://github.com/EpicPuppy613/maps/raw/main/Castle%20Assault.zip

**Comment by EpicPuppy613** [comment]
Update: I am currently working to update this using the new payload objective and adding a different win condition for defenders

**Comment by EpicPuppy613** [comment]
## Update 1.2.0
- Changed out flag objective for a payload objective
- Updated XML
- Fixed superflat world generation

XML: https://gist.github.com/EpicPuppy613/27d08c7d3febd35f43e9a7ee7bfc7d71
Download: https://github.com/EpicPuppy613/maps/raw/main/Castle%20Assault.zip

**Comment by EpicPuppy613** [comment]
forgot to trim, dont add yet

**Comment by EpicPuppy613** [comment]
## Update 1.2.1
- Actually trimmed map this time

**Comment by Cazadorian** [comment]
Finally had a chance to look at this map, while I do like the idea you're going for the map itself likely needs a lot of work:
- The map is very empty with little going on for large chunks of it. The initial payload stage is just a flat field filled with cactus, and then some trees. The castle itself does have some height elevation changes, but then inside of it it's once again just a flat platform with some trees around the edges. Even with the ability to build, it's still just too empty and flat.
- The entire map is just a straight line, you could legitimately complete all three objectives without moving any direction but directly forward. Having the entire map just revolve around running in a straight line across a flat field isn't going to work too well.
- Having a short section of the castle wall as a monument doesn't really work in my opinion. The only thing that really indicates the section you're supposed to destroy is that there's a line of obsidian in front of it, and the rough idea seems to be that you're blowing a hole in the wall to get into the castle yet you have to blow up most of the wall to complete it despite being able to get in without doing so. It may make more sense to either A. Have the entire wall be destroyable but not a monument B. Use structures to automatically blow up that part of the wall when you've completed the payload since the idea is that you're pushing explosives to blow up the wall, or C. Potentially make the last objective a monument, and instead require players to capture a control point in order to open the gates to get into the castle.
- There's a lot of filtering issues still with the map. Defenders spawn with stone bricks they can't place, you can place blocks at any time to replace grass/dead bushes including ones you can't normally place, trying to place a pressure plate at any time tells you TNT is disabled until after the payload is captured even if you have done so. 

I think it may overall be easier with this map to try to redo it with a different design but the same concept, as there's a lot that needs to be changed here. This is ultimately up to you to decide though.
