### ISSUE TITLE
[TDM:Scorebox/15v15] Anvil

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/CommunityMaps#6]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Anvil

## Gamemode & Map Description  
Anvil is a TDM game-mode which was designed to bring back a bit of the old OC nostalgia by taking inspiration from uboat koing and facility to make a warehouse style TDM map. I envisioned this map to be a fast-going PvP experience with it's linear layout and side tunnels/alleys and thought having an indoor factory like setting might really suit the map. I might need to make the tunnels/alleys wider or devalue bows a bit more if the meele aspect of the map is lost with 10 players per team. I've also tried to balance out meele with bow combat making it a bit harder to get arrows and not having an infinite supply + having proj prot on armour.

## Team Sizes
The map is designed with 10 players per team in mind... but can go to 12 if teams overflow. This may seem like a bit much for a micro-map considering the size but when testing with 2 players I thought the map would do fine with 10 players per side

## Screenshots
https://imgur.com/a/braB4Lf

# XML
https://gist.github.com/technodono/6c06362eb671d732e55ed6dd0d0dd71f

there is also a copy of the xml provided in the world download

# Map Image

![map](https://user-images.githubusercontent.com/22761234/89731355-ccd35c80-da89-11ea-9775-0418e7ee5315.png)

There is also a copy of the map.png included in 
the world download

# Download Link

[Anvil.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5047440/Anvil.zip)

the download link has been attached via github... I hope that is ok

This map has been edited to fix & implement some suggestions including the xml you gave me which was broken on my testing? a simple kit name change fixed that all:

[AnvilNew.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5074009/AnvilNew.zip)

New 1.0.1 download:

[Anvil 1.0.1.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5173839/Anvil.1.0.1.zip)

# Patch notes

**1.0.1**

- Added scoreboxes
- Added new splash poison potions as "exploration one-off" items 
- More bread!
- Increased player count - 10 > 14
- Tweaked map to have islands in water
- Added new tips

**1.0.2**

- Score boxes scores are now 3pts (5pts > 3pts)
- Removed end dimension tag
- Made it easier to kill players (Iron leggings are now chainmail) 
- Increased player count - 14 > 15 cause it felt odd + slightly empty on map
- Increased overflow 16 > 18ppl
- Unformatted most of the tips

**1.0.3**

- Some stairs are now gone
- Middle has been cleaned up
- You now start with better weapons
- Spawns are fixed
[Anvil 1.0.3.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5217591/Anvil.1.0.3.zip)

**Comment by Pugzy** [comment]
Just checked out this map and it seems like a solid submission.

### XML

XML works but I've made a few [tweaks](https://gist.github.com/Pugzy/438231e1d5b1fc2fa31a8845b2cc958c/revisions) to it can be found [here](https://gist.github.com/Pugzy/438231e1d5b1fc2fa31a8845b2cc958c)

- Moved spawn module definition below teams.
- Removed random kit element from `cuboid` region.
- Set blue team to use regular blue rather than dark.
- Updated team ids to use `x-team`.
- Removed `game` name from map so PGM can use its own translatable version.
- Removed `obs` kit and applicator (doesn't do anything/not needed).
- Fix general indenting.
- Observer spawn can put you quite near a wall, not changed this but something to note.

### Map
- It would be nice if both edges of the map had a way to get in to mid, one has the jump pad, dropdown and gangways and the other only has a staircase, makes this corridor feel a little cramped. 
- We would have to see how it plays but the water seems like a real pain if you fall into it as the nearest ladder can be upwards of 10 seconds of bobbing away (maybe more ladders or depth strider to make this faster).
- I'm not sure what the gameplay would look like (it could be great) but my first impressions leave me wanting more. You describe uboat as your inspiration but that map had two versions (one with scoreboxes and one with a control point) it could be that this map needs something similar to streamline players across the map.

Overall happy to test this map if you are online (and the player count fits). Working my way through the other maps and will probably scatter them in among the setnexts over the weekend, this map has a lower player count so this may need playing on a week day.

**Comment by technodono** [comment]
Thanks for the feedback... I will happily prune the chunks on the map (not sure how I forgot that but). On a weekday of in server downtime I’d be happy to test and see how the map plays. 

I considered CTP but had no idea wether it needed an objective like that or not due to only being able to test with 1 other person at a time. If testing proves the water too much of a slog I’ll probability add depthstrider boots to the kit as a fix.

Finally for the left side I wanted to have a way down but the conveyor belts got in the way of that... this however is really dependant on testing and will be fixed if it becomes an issue

**Comment by technodono** [comment]
hotfix is attached under anvilnew.zip by the way

**Comment by technodono** [comment]
@Pugzy  map's been updated... I suggest you check the changes

**Comment by Pugzy** [comment]
Updated, modified a few XML bits so you should fetch the most recent version from the repository.

Please stop with the use of ⚠and excessive formatting within tips and warnings.
Not sure why the map was set to use `the end` dimension, its an indoors map so I see no reason for this.

Does the map have any use for breaking/placing as the player can be put in adventure mode to prevent them from breaking the cobwebs making it easier for them to enter the scorebox.

**Comment by technodono** [comment]
> 
> 
> Updated, modified a few XML bits so you should fetch the most recent version from the repository.
> 
> Please stop with the use of ⚠and excessive formatting within tips and warnings.

Aight got it

> Not sure why the map was set to use `the end` dimension, its an indoors map so I see no reason for this.

That was an artifact from testing... i'll remove it

> 
> Does the map have any use for breaking/placing as the player can be put in adventure mode to prevent them from breaking the cobwebs making it easier for them to enter the scorebox.

There are 2 hidden boat items that the players can place/break... that's why they are not in adventure mode. The boats just being a fun secret and a refence to uboat

**Comment by master00ofdsiware** [comment]
This was played tonight, here are my thoughts based on the match:

- In the main hallways (to the left and right of spawn), bow spamming was the dominant tactic. It just isn't great that you can shoot someone through the entire hallway; I would suggest adding some spots to hide from bow fire, as well as breaking up the air in the hallway so that you can't shoot across the entire map; some carefully placed iron bars could help with this.

- Please capitalize the "c" in the Box Cutter sword's name.

**Comment by Pugzy** [comment]
To add to this can you expand the scorebox, deny zone, and portal regions down by one block. You posted an issue in the discard earlier in the week that showed using a boat to glitch points. Not sure how many boats are on the map but they allow you to enter the lowest block of the region (as the boat makes you 1 block tall) making the issue you mentioned possible.

**Comment by CrazyisCreeps** [comment]
A super small feature, but do you mind if I disabled the use of anvils and furnaces? Just so if you accidentally right click on one of them, it doesn't open the gui and take you away from the fight

**Comment by technodono** [comment]
@CrazyisCreeps yea sure

**Comment by master00ofdsiware** [comment]
Looks good to me. I have added this map to the Micro map pool.
