### ISSUE TITLE
[CTF/24v24] Tall Shot

### ISSUE THREAD

**Issue by lkfjimmy** [OvercastCommunity/CommunityMaps#618]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Tall Shot

### Gamemode & Map Description

Capture the Flag
Inspired by Long Shot, but in vertical.
Reach to the top and fall back to spawn.

### Team Sizes

2 teams 24v24

### XML

https://gist.github.com/lkfjimmy/0a9c885aab4ce0977b4a47f1132be466

### Map Image

![map](https://user-images.githubusercontent.com/110178996/214547971-b8b26b7f-854b-4698-acf1-fccd7e2b8e64.png)

### Map Download

[Tall Shot.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10773688/Tall.Shot.zip)

**Comment by lkfjimmy** [comment]
Updated Version 1.1.0

- Change Jump Kit to Fly Kit
- Stationary Water
- Narrow down Playable Area
- Minor fixes in map (add item frames to chest in blue spawn, more fire charges in chest)

[Tall Shot.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10533488/Tall.Shot.zip)

**Comment by lkfjimmy** [comment]
Updated v1.1.1

- Partially fixed fall damage when exiting fly area
- Added restriction area to prevent straight fall from the flag spawn
- Allowed fly kit even if carrying flag (in order to fix force death when capture)
- Added resistance at team spawn

[Tall Shot.zip](https://github.com/OvercastCommunity/CommunityMaps/files/10773664/Tall.Shot.zip)

**Comment by Cazadorian** [comment]
Initial feedback on this map:

- I don't think the fly kit to exit spawn is the best idea. It's going to confuse a lot of players, and I can already see a ton of people trying to fly out into the void and dying. I believe also that laggy players are able to keep flying for a few seconds  after the kit is supposed to remove it, and if someone was extremely laggy they could theoretically get to the other team's side or partway up the map from it. It may make more sense to replace it with a jump pad, or a horizontal spawn.
- At the moment the second a team makes it to the flag, they have essentially won and just have to wait for the respawn time to do so as you can easily drop directly from the flag post to spawn to capture it. Even if the ability to drop off the flag platform and strafe down into the spawn was blocked off, you can still water drop or simply have your team create a pool of water below to drop into. On Longshot most of the match time is spent fighting to get your flag back to spawn, with only the initial stage being bridging towards it. This map essentially is limited to just that initial stage as a result.
- I would personally suggest giving this make a unique aesthetic rather than the current adaptation of Longshot's aesthetic, but that's ultimately up to you.

**Comment by lkfjimmy** [comment]
The idea of making a parody map for Long Shot is terminated from now.
Here leaves a few responses to caz's comments:

- The fly kit is chosen eventually as it's the best solution I can make with the minimum edition to the map.
- The falling to capture idea seems to be easy but the other team also get an advantage to go to the enemies team easier. When compared to Long Shot, there is no deny region in this parody so it will be much more easier to kill the one carrying flag.
- The adaptation of Long Shot's aesthetic is intentional for a parody, as less change to it as I can.

Just a bit disappointing that map dev doesn't give a shot to the temporary fly kit idea that's never implemented in other maps and seems like the standard of map submission is not welcoming a parody map.
