### ISSUE TITLE
[Blitz Rage TDM/12v12v12v12] Player Blender

### ISSUE THREAD

**Issue by Zynnphony** [OvercastCommunity/CommunityMaps#648]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Player Blender

### Gamemode & Map Description

Blitz Rage TDM, similar to Charge and Charge 2.0. 

Players will be split into 4 teams. Upon match start players will fall down their spawn chute and be launched into the blender where they can kill other players instantly. Last team to survive wins

The blender has a large launchpad at the bottom to keep players moving

Concept image (not final)
![image](https://user-images.githubusercontent.com/85294819/218119272-3f1f2b47-17f9-43a9-bbdd-f74954ebd2a8.png)

### Team Sizes

4 teams of 12 players

### Screenshots

https://imgur.com/a/d97r9XC

### XML

https://github.com/zzuf-fer/zzuf/blob/main/player_blender/map.xml

### Map Image

![PlayerBlender](https://user-images.githubusercontent.com/85294819/218120947-88211471-7f95-4a0e-a2f8-b9583a969364.png)

### Map Download

https://www.mediafire.com/file/fb2kmu3weflwoyo/player_blender.zip/file

**Comment by technodono** [comment]
Was wondering if you could confirm that you built that blender model. I know I may sound very pushy & rude but I'm just being on the safe side with this one since we've had new members download maps of pmc & pass it off as their own in the past. This isn't a usual message and the answer will likely just show that you can build a cool looking blender 🥇 

Keep building maps though, the start is promising 😄 

Many thanks,
Builder Technodono

**Comment by TjebbeLeen** [comment]
Hey @technodono ,

No worries! Glad you guys verify the submitted builds. I did build the blender last week. I’ll take it as a compliment that you thought it could have been copied :P

I’m a builder at Shapescape and have been building for them for the last 7 years. I also made some other maps for other servers including Tuscany Hills, which is also live on Overcast

**Comment by technodono** [comment]
> Hey @technodono ,
> 
> No worries! Glad you guys verify the submitted builds. I did build the blender last week. I’ll take it as a compliment that you thought it could have been copied :P
> 
> I’m a builder at Shapescape and have been building for them for the last 7 years. I also made some other maps for other servers including Tuscany Hills, which is also live on Overcast

Oh that's very lovely! Glad to see some experienced builders get into the mapmaking groove! enjoy the excellent response and hope the map plays well 🙏

**Comment by TjebbeLeen** [comment]
zzuf updated the map with adjustments to the launch pads which should now function consistently

new map download:

https://www.mediafire.com/file/9w6mr2tnwmp6x9e/player_blender.zip/file

**Comment by Cazadorian** [comment]
Feedback after seeing this play:

- Players can currently get stuck on the side of the blender with no way back up, and the only way for anyone to kill them is to fall down and also get stuck. Not sure the best solution to this, potentially another jump pad down below or a portal back to spawn if you fall past a certain Y level but up to you how to solve this.
- After the initial few seconds the map just becomes a few people bouncing up and down until they manage to get the last few kills due to players being eliminated very fast. I think the map may play better if the time limit was reduced to maybe 2-3 minutes, and it was turned into a TDM rather than a blitz map. This would result in more players constantly being shot into the blender which should keep the map fast paced.
