### ISSUE TITLE
[DTM/20v20] Island Divide

### ISSUE THREAD

**Issue by EsotericSorcery** [OvercastCommunity/CommunityMaps#668]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Island Divide

### Gamemode & Map Description

Island Divide is a 20v20 DTM map set on a tropical island split into two. Each half contains two monuments—one obsidian and one emerald—which must be destroyed by the opponent (if they care about winning). 

### Team Sizes

20v20

### Screenshots

https://imgur.com/a/vE1abAd

### XML

https://gist.github.com/EsotericSorcery/162cb276746310621538f1e71561c9e4

### Map Image

![Island Divide](https://user-images.githubusercontent.com/107477007/228031576-8d646e36-1cda-4dc1-a40e-9e6097c14e07.png)

### Map Download

[Island Divide.zip](https://github.com/OvercastCommunity/CommunityMaps/files/11081851/Island.Divide.zip)

**Comment by Cazadorian** [comment]
Initial feedback on the map:
- Red and green together are generally best avoided for team colours due to them being hard to distinguish with common forms of colour blindness. I'd recommend changing at least one of them to another colour to avoid this.
- I'd remove the secret chest under the map filled with diamonds, having a secret chest that allows someone to potentially get full diamond on a map with leather kits is extremely unbalanced.
- More items should likely be added to item remove as your inventory is going to get cluttered very fast from all the little bits on the map like bookshelves, flowers, melons etc. Buckets should also be added to itemkeep as at the moment they drop on death both when full and empty while also being part of the spawn kit. Arrows should be added to tool repair or item remove as well.
- I'd potentially just change the bucket in the spawn kit to a full bucket, spawn is already surrounded by water so there's not really much of a reason to require people to fill it up while running out of spawn every time.
- The delay on the golden apple spawners in middle is extremely long for a map like this. I'd maybe reduce it to about 8-10 seconds instead.
- The water that flows over the edge of the map is going to cause some oddities with the void filter used as it'll count as non void as long as the water is there at y0, and if removed it'll start being counted as void stopping any further building. I'd either adjust the filter or edit the water so it ends one block higher up.
- Obs spawn can be reached from red's side by pillaring up and boating over so I'd maybe push it back a few blocks. This is minor though and isn't an absolutely needed change.

**Comment by EsotericSorcery** [comment]
The map has been updated according to the feedback. I fixed the void issue by adding the problematic water edges to buildable regions (if anyone knows a more elegant solution, be my guest). It should be OK now.
