### ISSUE TITLE
[Update]Kerskyn, 1.0.1

### ISSUE THREAD

**Issue by oafMH** [OvercastCommunity/CommunityMaps#698]
### Checklist

- [X] The updated map files are [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks), or the update is XML only.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The update has been tested locally to make sure it works.

### Changes

Swapped one of the smaller trees on the second island with the one in front of the wool room as the size of the tree made it quite difficult to defend

Added shears to spawn kit to make it easier to remove trees

### XML

https://gist.github.com/oafMH/d5c467bd465c2610b59cb6628369ac8b

### Download Link

https://www.dropbox.com/s/fjojvkuu821dyq3/kerskyn_update_pruned.zip?dl=0

**Comment by TheRealPear** [comment]
Thanks for submitting a map update. I wanted to clear up some questions about this before committing. This map is already on version 1.0.1 in the CommunityMaps repo, so I'm assuming it's meant to be 1.0.2?

As for the loadout, you have iron gears in the kit yet you have stone gear in `itemremove` and `toolrepair`? Was this intentional? Players will start dropping the tools they spawned with as it's not listed in either module.
![XML diff](https://user-images.githubusercontent.com/20259871/233846271-58abdbd7-5c94-4e89-adbf-bc62fc9898d0.png)

**Comment by oafMH** [comment]
How could I have been so foolish! Here is the updated XML without any mistakes (hopefully) thanks to my good friend samschaap!
