### ISSUE TITLE
[KOTF/20vs20] Crystal

### ISSUE THREAD

**Issue by Oprad1** [OvercastCommunity/CommunityMaps#712]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Crystal

### Gamemode & Map Description
**[KOTF] Control the flag with your team for 200 seconds to win.**

![mHKml2N - Imgur](https://github.com/OvercastCommunity/CommunityMaps/assets/132610098/1a380a6c-2936-4192-9b6a-9d03a92459df)
The first flag spawn in the middle, depending on which team take it, it will respawn the opposite team.
~~3 different spawn on each side
~~Double jump every 8 seconds
~~Jump pad / Slime block / Secret chest
~~No fall damage
### Team Sizes

20

### Screenshots

https://imgur.com/a/RCscFxi

### XML

https://gist.github.com/samschaap/62bb29860b995350d0bb31972bf18442

### Map Image

![map](https://user-images.githubusercontent.com/132610098/236528929-297203e6-14f2-4091-b6cf-594006a9a3be.png)

### Map Download

https://cdn.discordapp.com/attachments/1103319894054932531/1108739119191953439/crystal_1.0.1.zip

**Comment by TheRealPear** [comment]
Congratulations on your first map submission!

I love the design of this map, however, I have a few suggestions. Whether you implement them is completely up to you.
* It is somewhat difficult to find the flag at the center, as seen here. In my case, I did not have a full bright mod installed. It might be a good idea to give people a kit with permanent night vision or add more lighting around this area.
![image](https://github.com/OvercastCommunity/CommunityMaps/assets/20259871/274a252d-b38d-4795-907b-3a8cafde00e0)
* For a map with a lot of height variation, it might be best to decrease the recharge time for double jump.
* The three spawns per team are all facing the same direction, which might be confusing since it doesn't always align with the nearest path. You can consider using the [`angle` attribute](https://pgm.dev/docs/modules/mechanics/spawns#regions-element-attributes) instead of `yaw` in the XML to automatically face the players toward the center of the map, depending on which location they spawned at.
* There should be more visual cues around the jump pad areas so players can find them more easily.

**Comment by Oprad1** [comment]
Thanks Pear, This is actually my first map and i'm open to any suggestions. Me and Samschaap worked on your points and the files are re-updated.
- The light around the middle is now brighter :
![2023-05-18_15 42 12](https://github.com/OvercastCommunity/CommunityMaps/assets/132610098/c0062799-bdf6-4b25-9090-a00357889c2f) 
- We decrease the recharge time of double jump to 8 seconds.
- We add angle to spawn location depending on where we want them to go.
- We add new visuals : 
![mHKml2N - Imgur](https://github.com/OvercastCommunity/CommunityMaps/assets/132610098/1a380a6c-2936-4192-9b6a-9d03a92459df)
![u6aaZvn - Imgur](https://github.com/OvercastCommunity/CommunityMaps/assets/132610098/f7f482d6-1936-4287-b3f5-8c5f3b0858af)
![Ms6UPSf - Imgur](https://github.com/OvercastCommunity/CommunityMaps/assets/132610098/66355030-7fc2-4365-8d07-8e213a2bde27)

**Comment by TheRealPear** [comment]
Your map will be loaded onto the server shortly. I'll go over this just to make sure you understand what you can do next:
* You can ask any OCC staff to queue your map whenever, we recommend taking advantage of this so you can see how the map will play out with normal players and make any adjustments if necessary.
* At the moment, this map will not be sponsorable until it is thoroughly tested. This is a standard procedure for all new maps that will be removed after a while.
* A spot in the pool is not guaranteed as that is something that is done monthly over a discussion between map developers (and occasionally, the community).

I will keep this ticket open for any future map updates. It will be closed and marked as complete once we feel that this map is fully complete and good to go. Once again, thank you for the submission!
