### ISSUE TITLE
[RACE/16 Players] Blockglitch

### ISSUE THREAD

**Issue by StanleyThat** [OvercastCommunity/CommunityMaps#73]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Blockglitch

## Gamemode & Map Description  
Blockglitch is a /setnext race map where players must jump over hurdles (by glitching over them) Block glitching is allowed. There are three laps and PVP is enabled. This map will be best suited to people with bad ping, but users with good ping are still able to participate as we have tested it. Additionally, players can neo jump around walls instead of block glitching too.

## Team Sizes
16 Teams, 1 player per team.

## Screenshots
https://imgur.com/a/A4mn8WZ
  
# XML
https://gist.github.com/StanleyThat/c78cb559dc842512b191a71514356f65

# Map Image
![map](https://user-images.githubusercontent.com/73564460/97382503-40f9ff80-1917-11eb-976c-b080c3863676.png)

# Download Link
**Dropbox**.
https://www.dropbox.com/s/35v1x58t2usgcdk/Blockglitch.zip?dl=0

**Comment by technodono** [comment]
may want to mention that it's a /setnext map other than that... good luck

**Comment by CoWinkKeyDinkInc** [comment]
This map is based

**Comment by StanleyThat** [comment]
> may want to mention that it's a /setnext map other than that... good luck

Done!

**Comment by CrazyisCreeps** [comment]
Gotta say I love that went through with this and made the map 😆 

I'll test out the XML and if it's all good I'll get it play tested a few times

**Comment by CrazyisCreeps** [comment]
Xml seems to work fine, but I am curious if you'd give it any thought to extend the size of the lanes and add more slots for players? This would allow us, the staff, to be able to set the map at any time without the worry of the map being too crowded to be able to place down any blocks. As a point of reference, any time I set maps there's at least 30 players online, if not more.

Secondly, not sure if it's intentional or not, but with 1 block thick walls, people can simply circle jump around the walls and avoid block glitching all together. If this was intentional to allow for people who can't block glitch to see pass, that's understandable, but otherwise you may want to look at making the walls a little thicker. Or, maybe extending the wall out past the lane, and allowing players to attempt to block glitch around it in order to get by 😉

**Comment by StanleyThat** [comment]
> Xml seems to work fine, but I am curious if you'd give it any thought to extend the size of the lanes and add more slots for players? This would allow us, the staff, to be able to set the map at any time without the worry of the map being too crowded to be able to place down any blocks. As a point of reference, any time I set maps there's at least 30 players online, if not more.
> 
> Secondly, not sure if it's intentional or not, but with 1 block thick walls, people can simply circle jump around the walls and avoid block glitching all together. If this was intentional to allow for people who can't block glitch to see pass, that's understandable, but otherwise you may want to look at making the walls a little thicker. Or, maybe extending the wall out past the lane, and allowing players to attempt to block glitch around it in order to get by 😉
> 
> I'd also probably disable fall damage. It's not a huge change, but its a quality of life sort of thing imo

I will increase team size and lane size

Yes the 1 thick walls is intentional, I heard some people say good ping might be an issue, I tested it a bit with someone with good ping and they said they were able to block glitch fine, but the 1 thick walls is just a safe measure incase people still cannot jump around :)

**Comment by KingOfSquares** [comment]
This is very nice, a good party map!

**Comment by StanleyThat** [comment]
Made some minor changes: 
Updated team size to 50, increased lanes and disabled fall dmg.

Map:
https://www.dropbox.com/s/9sop9ulk44ab70s/Blockglitch.zip?dl=0

XML:
https://gist.github.com/StanleyThat/99f17ac0b7ead40d71c977e95b558b21

New images:
https://imgur.com/a/dJExpJM

**Comment by CoWinkKeyDinkInc** [comment]
I fixed the XML because you accidentally made the people in the starting line start at the same point. I also suggest adding lighting around the spawn island and the beginning of the map so that players can read the signs more easily. Also I ran into lag issues with the lighting when breaking the bottom layer of the blocks as an observer so I think you should make the platforms one block thicker to prevent this. https://pastebin.com/bst5vSH5

**Comment by StanleyThat** [comment]
[BlockGlitch.zip](https://github.com/OvercastCommunity/CommunityMaps/files/5470022/BlockGlitch.zip)
Okay just fixed those things :)

**Comment by CoWinkKeyDinkInc** [comment]
I just played a match today and it just came to me that I probably should've added more than one bedrock into each inventory slot. This probably would've made blockglitching a lot more easier and the map less tedious to complete.

**Comment by CrazyisCreeps** [comment]
Honestly I think this is as good as it's going to get, it sure is an interesting map, makes me wish I had horrible ping haha!
