### ISSUE TITLE
[CTW/24v24] Acapulco

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#767]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Acapulco

### Gamemode & Map Description

If you want to go on vacations we recommend all of you Acapulco, but this time... is not a safe place, each team will try to get into the hotel of the enemies to get the wool and return it to their main hotel to win.

### Team Sizes

24v24

### Screenshots

https://imgur.com/a/OvMZqn6

### XML

https://www.dropbox.com/s/pqy1csyuc1jjxo2/map.xml?dl=0

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/fa1aef1e-d69f-4733-b599-a16a5ac82da1)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/a23d2a6a-dabe-4e1d-936f-27394b26f19f)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/e94669bc-e508-49b5-bf2a-1e38cf91e7d0)

### Map Download

https://www.dropbox.com/scl/fo/joxjetf1mjfby9cf73r70/h?dl=0&rlkey=cocrth5l4e1d2zncbo3z06r3e

**Comment by arcadeboss** [comment]
Looks great, nice trees.  Palm in base cool detail.

Your description above is amusing, your game could have similar information for players by adding "tips" to your XML.

**Comment by Lexnardo11** [comment]
True, that's something that I always forgot to add

**Comment by Strangeys** [comment]
Lanes are very wide but should hopefully counter the possibility of stalemates happening. I went ahead and moved the spawn deny-block region out further so that a staircase to sky isn't far back to give a bigger platform to shoot at incoming skybridge attacking the wools. I feel like the map can still stalemate easily due to how short the distance is from respawning players to defend where as trying to attack the enemy wool will be a far run. I'll add this to the upcoming pool update but if it has issues stalemating, it will get removed quickly until updates are made to prevent it.

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
