### ISSUE TITLE
[CTW/12v12] Sakura Garden II

### ISSUE THREAD

**Issue by Lexnardo11** [OvercastCommunity/CommunityMaps#768]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Sakura Garden II

### Gamemode & Map Description

A sequel from our first map in OCC...

Sakura Garden II is the part II of one of our projects on the server, this time we are giving to the players a small version of an oriental themed map.

### Team Sizes

12v12

### Screenshots

https://imgur.com/a/UqaBbXF

### XML

https://www.dropbox.com/s/s5xw3ux6j6esttf/map.xml?dl=0

### Map Image

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/176ccf21-f2a3-4608-8ce3-7883aee997dc)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/bc605990-b2c0-4e1a-985b-d2a8fce0d332)

![image](https://github.com/OvercastCommunity/CommunityMaps/assets/99238656/ec51fc8c-2cc6-4ff4-9551-e7fdf50309fe)

### Map Download

https://www.dropbox.com/scl/fo/57rhzckbw0bvesga22g09/h?dl=0&rlkey=9fdmsus7vlswto2ged19t450t

**Comment by arcadeboss** [comment]
Beautiful.

The center structure is awesome.   And I like the details in the base for the wool rooms.

**Comment by Strangeys** [comment]
You have a bedrock block on the edge of the main land of red's side. I'd suggest lowering the island in front of spawn by a block so you have better visibility of what's on the map. The wool room gear is OP, I'm not sure why you need to enchant the chestplate and boots with protection 1, I'd rather see them have no enchants. I went ahead and swapped the stone sword with iron in the kit because it's annoying for players to need to craft an iron sword. I upped the blocks in kill reward too since we generally do 1/4 of the given blocks in the kit as kill reward.

I'll load it up and likely throw it in the upcoming pool update. The layout looks fine and I don't think it will have any notable stalemate issues.

**Comment by Lexnardo11** [comment]
> You have a bedrock block on the edge of the main land of red's side. I'd suggest lowering the island in front of spawn by a block so you have better visibility of what's on the map. The wool room gear is OP, I'm not sure why you need to enchant the chestplate and boots with protection 1, I'd rather see them have no enchants. I went ahead and swapped the stone sword with iron in the kit because it's annoying for players to need to craft an iron sword. I upped the blocks in kill reward too since we generally do 1/4 of the given blocks in the kit as kill reward.
> 
> I'll load it up and likely throw it in the upcoming pool update. The layout looks fine and I don't think it will have any notable stalemate issues.

We just made some changes of it, the fixed map is on the builders dropbox, we changed the kit in woolrooms for diamond chestplate and P1 iron boots

**Comment by TheRealPear** [comment]
Closing this as this map has been in the pool since July 2023 without any major issues. Thank you for your submission!
