### ISSUE TITLE
[KotH/16v16] Bookshelf x64

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#79]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Bookshelf x64

## Gamemode & Map Description  
Theme: Inside of the bookshelf block
This is a 4CP KotH map which has large height difference. Players must capture 4 point and gain 1000 points. I hope this will liven up the micro pool, which is starting to get tired of the same maps.

## Team Sizes
16v16 (for micro)

## Screenshots
[Imgur](https://imgur.com/a/ITnzJ9A)

# XML
[Gist](https://gist.github.com/Pe241/271f73fd10a0887da291ea8c0009801d)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/98127494-1ea94880-1efa-11eb-8a7e-8c75c16d0186.png)

# Download Link
[v1.0](https://drive.google.com/file/d/1-XCEnVKTuNpd-FFvm008ByZlb9UFsPTB/view?usp=sharing)

**Comment by KingOfSquares** [comment]
Love the item names! 😆

**Comment by Pugzy** [comment]
Please don't use shorthand or abbreviations for ids as it makes it harder to read.

**Comment by Pe241** [comment]
> Please don't use shorthand or abbreviations for ids as it makes it harder to read. 

I'll fix it when make to change other point.

**Comment by master00ofdsiware** [comment]
I like the concept, but the gameplay is not something I'm a fan of. Hopefully it can be improved, as I would definitely be interested in adding a fixed version of this to the map pools.

The gameplay is overall disorganized. This is caused by the very open layout of the map, combined with it being difficult to traverse and having multiple randomized spawnpoints that are fundamentally very different to the player. I'd like to explain why all of these are unfavorable:
- The map has an open layout, as seen by the ability to jump down from the higher level to lower ones, and the central level with the A and B hills has no railings. This is in contrast to most hill maps, where the map naturally directs players along certain paths towards the hill; this gives players a better sense of where to go and allows them to be better organized. I found that players on Bookshelf were jumping all over the place in a disorganized fashion, which does not make for a fun game.
- The map is difficult to traverse upwards. Once you're on the central level, the only way to get back up is by taking very thin stairs. This, combined with the ease of getting knocked back down, makes the upper hill very annoying to get to unless you just spawned at the upper spawnpoint.
- The way a player moves relative to the objectives is very different depending on which spawnpoint they get spawned at. You get swarms of players attacking the upper hill from the upper spawnpoint, and players from the lower spawnpoint wander towards the three other hills, but have basically no reason to attack the upper hill.

My suggestion would be to reimagine the layout such that there is one spawnpoint per team near the central height, and the map is easily traversable from this area. The hills can still be at different levels, but they shouldn't be too close to the spawnpoint as the upper hill currently is. They also shouldn't be punching arenas like the current A and B points. Maybe designing some tunnels or bridges with railings would help, so that players have more defined paths from the spawn. I suggest looking at many other hill maps to see how they are traversed, and drawing inspiration.

**Comment by calcastor** [comment]
In hopes of garnering a wider range of player feedback on several pending yet 100% functional community maps, I've gone ahead and added many of them to the pools. This map has been included in that, and I hope to be able to collect at least the most prevalent feedback on the each map to post in their respective issues pages.

**Comment by Pe241** [comment]
🏳
