### ISSUE TITLE
[DTM:AD/30v30] Zombie Defense

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#8]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
~~Zombie Defense DTM~~→Zombie Defense DTM:AD

## Gamemode & Map Description  
Theme:Zombie Defense & Zombie raid on the fortress

This is a DTM&Attack/Defense map. Zombies(Attackers) must destroy the central Villager monument within 15min and Steves(Defender) must defend it. Zombies are coming at Monument from 360°, so Steves need pay attention to all directions.
I'm grateful to everyone for their advice in Discord and I hope everyone enjoy it.

## Team Sizes
~~25vs25 (centi, hecto or both?)~~ →30vs30 (hecto?)

## Screenshots
[Imgur](https://imgur.com/a/p6u7QnH)

# XML
[Git Gist](https://gist.github.com/Pe241/857749a2e2bb9a10ffd887e24d52eb3d)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/90271024-21b21100-de96-11ea-9b77-71d4591a4434.png)

# Download Link
[v1.0.0](https://drive.google.com/file/d/1mM7UfUJ8cZkQWJC51GuEmxncad1Ns-t4/view?usp=sharing)
[v1.0.1](https://drive.google.com/file/d/1ulwbzik31b0_SOCw4LZ4bX5DMZRVviQZ/view?usp=sharing)
[v1.0.2](https://drive.google.com/file/d/1BCZP8mu6WVDjyeWyoIgLup2NH-gzPFJ5/view?usp=sharing)

**Comment by Pe241** [comment]
### Update to v1.0.1

### Changed and Fixed in XML

-  <killreward(s)> → <kill-reward(s)>

- Changed max players 25vs25 → 30vs30

- Became Players can't see enemy's nametag.

- Added plural="true" in <team>

- Added color code to Skull_item's name and entry prohibition message.

- Adjusted the filter message.

**Comment by fixitqixit** [comment]
This map was much harder for me to review than Bomber Guys for sure. Theres many aspects of this map that will need to be reviewed once the following changes/suggestions are implemented or taken into consideration:

- I think the title of the map should be changed to, or include the symbols of A/D or Attack/Defend (probably too long). So maybe the title of the map would be Zombie Defence A/D? I'm not sure, but I feel like its slightly confusing.
- The villager monument should also be changed to maybe Villager Monument instead of just Villager.
- TNT in the attacker spawn kits I think should be changed. It becomes really chaotic with how much tnt they have. One suggestion I have is if you want the attackers to cannon I would keep them spawning with their default kits, but when they cross a certain point of the map and start getting closer to the monument they receive a new kit that has less tnt and supplies so that it makes it harder to attack. I would suggest drawing on Zap: Cubist Remix for inspiration. I can supply the XML for that map as well if that makes implementing this idea easier.
- Defenders need to have more blast protection. Currently they just get obliterated by the onslaught of tnt. I think the tnt is really good for destroying the monument, though considerably less so for killing the opposing team.
- Some parts of the map as shown [here](https://imgur.com/a/B6OOCf1), [here](https://imgur.com/5GlQzyI) and [here](https://imgur.com/undefined) are seriously lacking detail. This is even more apparent on the long grass platforms. There are many options available for you to spruce these areas up and make them more visually appealing. I will outline them in the following point:
- You could change some parts of the map to be more simplistic in their block palette like BoomBox, Cos (tnt), Zap: Cubist Remix, etc. These maps employ stained clay, stained glass and quartz, among other simple blocks, to allow for straightforward map designs that are visually appealing. Some of the parts of your map try to have detail by using detailed more naturally occurring blocks (eg: grass, stone brick, cracked stone brick, stone, etc.) but the way they have been utilised is over-simplistic and underwhelming. Some of the structures too lack detail which is required for these map submissions. 

Besides all these points of feedback I really do enjoy the concept you've got going with this map, as I do with all your other maps! Good work with getting this done and I look forward to future updates on this map - which I think it will need before we can play it more.

**Comment by fixitqixit** [comment]
I thought I'd quickly just extend on my final points about the physical appearance of the map.  Maps made by the mapmaker Tywnis use a combination of simple blocks (like those mentioned above) as well as more natural blocks. His simplistic designs on his maps are very effective ways of building and I suggest studying the layout, design and block palette of his maps for some inspiration. When I first started off making maps I drew heavily on his designs and block palettes and I reckon it was really helpful for establishing my own distinct map making style. Hope this helps!

**Comment by Pe241** [comment]
@fixitqixit Thank you for feedback.
I wanna reference xml of Zap, where can I read this?
I searched [OCN Archives](https://github.com/OvercastNetwork/maps.oc.tc) ,[Resourcepile](https://mcresourcepile.github.io/), and [OCC archive](https://github.com/OvercastCommunity/maps), but could't find it.

**Comment by fixitqixit** [comment]
@Pe241 [Here](https://gist.github.com/fixitqixit/470db57360744da124db97970a2868e6.js) we go.

**Comment by Pe241** [comment]
Updated v1.0.2. Please check [pull request](https://github.com/OvercastCommunity/CommunityMaps/pull/18).

> TNT in the attacker spawn kits I think should be changed. It becomes really chaotic with how much tnt they have. One suggestion I have is if you want the attackers to cannon I would keep them spawning with their default kits, but when they cross a certain point of the map and start getting closer to the monument they receive a new kit that has less tnt and supplies so that it makes it harder to attack. I would suggest drawing on Zap: Cubist Remix for inspiration. I can supply the XML for that map as well if that makes implementing this idea easier.

Decreased Zombies TNT. I decided not to change kits by region. Players will be confused if kits suddenly change while bridged.
Shortened match time and made more difficult to destroy the monument.

**Comment by Pe241** [comment]
### Update to [v1.0.3](https://drive.google.com/file/d/1oz0dPbyxzYZ6K_cAKwiyfIrmErjoERed/view?usp=sharing)
##Change

- Kits order
![2020-09-09_08 18 49](https://user-images.githubusercontent.com/18105767/92536651-28edf400-f275-11ea-84ad-4bda4be5bf92.png)
![2020-09-09_08 19 03](https://user-images.githubusercontent.com/18105767/92536658-2c817b00-f275-11ea-9e57-c1dfc99c7649.png)

- Explosion Protect
Everyone can blow up: Void area, around the monument, Zombie side aerial, Steves side aerial
Nobody can blow up: Central grass area (y<=21), Roof and floor of the fortress, Wood deck, Battleground of Zombies side.
Only Zombies can blow up: Defense kits chests on the central grass area, wall of the fortress

Wrong cannon will blow up :P.

- Add tip about enchanted iron chestplate spawner

**Comment by fixitqixit** [comment]
@Pe241 In this update were more details added to the map to improve how it looks? I still think this is a major fix that this map still needs.

**Comment by Pe241** [comment]
@fixitqixit Added some design change in [v1.0.2](https://imgur.com/a/9XWFwHC). More update is needed?

**Comment by fixitqixit** [comment]
I like the changes you've made @Pe241 ! I changed the map name from "Zombie Defense DTM:AD" (which is too long and has incorrect spelling) to "Zombie Defence A/D". This is a more simplified title and more appealing.
I still feel like zombies should be given a new kit when they enter the middle island like on Zap: Cubist Remix. With all the tnt in their kits Zombies dont feel the need to make cannons and be strategic as attacking the monument head on is easier. I think Zombies get to the main castle they should be given less blocks, less tnt, and maybe the speed effect (?). This would make attacking the castle directly a lot harder and I think the game would be more fun.

**Comment by Pe241** [comment]
@fixitqixit Thank you for feedback!

> I changed the map name from "Zombie Defense DTM:AD" (which is too long and has incorrect spelling) to "Zombie Defence A/D". This is a more simplified title and more appealing.

"Defense" is American English, so it's correct.
Pugzy told me that not to use "/" in the map name. ([here](https://github.com/OvercastCommunity/CommunityMaps/issues/9#issuecomment-674990432))
Is that allowed? Which is correct?

**Comment by Pe241** [comment]
I'll rename Zombie Defense (or Defence) if it's too long and there is a problem.

**Comment by fixitqixit** [comment]
Just playing this now. I think Zombies should be able to damage the whole of the Villager base. Though maybe if you want there to be less destruction and chaos you could add renewables and make the base renew after a certain amount of time?

**Comment by master00ofdsiware** [comment]
This map was tested yesterday. Overall I like the idea of having an interesting-looking A/D TNT map; it's quite refreshing compared to CannonCube and BoomBox which are incredibly boring to look at. However, the map still needs a bit of work before it is well balanced. It may look like a lot of bullet points, but a lot of them are just simple XML changes.

- The monument should only be destructible using TNT, not via pickaxe. Having it breakable using a pickaxe makes it too easy for an attacker to hide inside the monument and break it from the inside.

- Water usage should be disabled near the monument, so that the defenders cannot create a water wall that is impenetrable by TNT.

- Disable block placement within the melon tubes, other than TNT and redstone blocks/torches. Players should not be able to place wood and such in the tubes.

Below, I'm going to refer to the rectangular platforms that attackers bridge to as the "main platforms"; these are the ones next to the zombies.

- The main platforms are too short. It is very difficult to aim a cannon from them due to how low they are compared to the monument. So I would recommend some kind of stacked arrangement where there are multiple levels attackers can occupy (similar to Zap: Cubist Remix). Before finalizing the layout, try loading the map in your local PGM server and attempting to cannon the monument yourself.

- It is too easy for defenders to completely destroy the main platforms using a relatively small amount of TNT. The platforms should be thicker in height, and consider giving the defenders a different kit with less TNT if they leave the central island (similarly to the varying kits in Zap: Cubist Remix).

- The main platform renewables don't seem to fully work, please investigate this and make it so that all the blocks renew.

**Comment by Pe241** [comment]
Thank you for feedback @master00ofdsiware .
I already made [PR](https://github.com/OvercastCommunity/CommunityMaps/pull/67). Check and merge this please.

> The main platform renewables don't seem to fully work, please investigate this and make it so that all the blocks renew.

Vine and skull are excluded from renewable. Cause I don't think vine revival is necessary & I think it's strange that vine is floating in the air & all zombie head become skeleton heads when these are repaired. (I'll make issue to PGM-github later.)
I changed "rate" to "interval" this time. However it may take many times to repair when many blocks were destroyed.

> It is too easy for defenders to completely destroy the main platforms using a relatively small amount of TNT. The platforms should be thicker in height, and consider giving the defenders a different kit with less TNT if they leave the central island (similarly to the varying kits in Zap: Cubist Remix).

I made less-TNT kit for steves who leave from their side, and set these platform repair faster than fortress instead of changing the thickness.

**Comment by master00ofdsiware** [comment]
This map is pretty close to being complete, but there are still several minor changes needed to make it balanced.

- It doesn't take much TNT to blow up the entire monument. To combat this, please make the inside of the monument out of endstone, since it has a higher blast resistance than stained clay. The outer shell of the monument can still be made of stained clay to preserve the Villager aesthetic.

- Attackers currently have too much TNT when they enter the central island. Let's try giving them 8 TNT instead of the 32 they get now, and we can make adjustments later if necessary. You can also give the attackers a special killreward in this region, of 8 more TNT; this allows them to continue making progress rather than being stuck with no TNT.

**Comment by Pe241** [comment]
@master00ofdsiware 
It seems that the difficulty level is increasing.
Should I extend the match time?

**Comment by master00ofdsiware** [comment]
> It seems that the difficulty level is increasing.
> Should I extend the match time?

Let's keep it at 10 minutes for now, and we can adjust it later if it is too difficult for attackers to complete the objective in the given time.

**Comment by Pe241** [comment]
Thank you for adopting this map :)
