### ISSUE TITLE
[CTW/40v40] Kingdom

### ISSUE THREAD

**Issue by Scripteding** [OvercastCommunity/CommunityMaps#881]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [x] The map has been tested locally to make sure it works.

### Map Name

Kingdom

### Gamemode & Map Description

Classic CTW gamemode taking battle out on fields of kingdoms!

### Team Sizes

2 Teams, 40 Each

### Screenshots

https://imgur.com/a/VmDxuoP

### XML

https://gist.github.com/Scripteding/4f27acc2efb48a190ee10cbde9200521

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/96262437/24ccbd8c-180f-43a4-800b-5d88094765e9)

### Map Download

https://drive.google.com/file/d/1ZIzNHRMLdvSeEf2AYYKFaeqMZLV6lnMC/view?usp=sharing

**Comment by Scripteding** [comment]
Updated XML & Tested Locally: https://gist.github.com/Scripteding/deb93845d945b36b0f05d146547c966a

**Comment by arcadeboss** [comment]
I like big maps, I cannot lie.

Appreciate your audacity on this.    350 blocks deep (spawn to spawn) and 200 wide (left wool spawner to right wool spawner) is one of the larger I've seen.

40 players per team, fat.

You are making me feel better about my 280 deep (spawn) x 240 wide (wool) map I'm working on that I thought might be too big.

**Comment by calcastor** [comment]
Would like to load this soon to at least get it tested. I am concerned it's too large to have a good match on but this wouldn't be the first map.

A couple notes:

1. I would avoid making the cobweb outlines a solid line of cobweb. It would be better to make them spaced out by 3 or so blocks, or even more than 3. Makes it harder to for players other than get stuck in.
2. Regardless of any XML workarounds, please extend the bedrock underneath the wool lanes to y-level 0.

**Comment by calcastor** [comment]
Some more notes, mostly XML side:

1. Use `<include id="gapple-kill-reward"/>`; to do so just add the line in quotes for the include but also remove the golden apple kill reward.
2. This needs golden apples, wood planks, and stained glass in `<itemkeep/>`.
3. Given the size of this map, players should have two stacks of wood at minimum. I would consider raising the stained glass to a full stack as well.
4. I would double the kill reward amount to 32 and 16 for wood and glass respectively.
5. Is glass as a kill reward instead of `team-color`'d stained glass intentional?

**Comment by Scripteding** [comment]
@calcastor Thanks for the feedback, I should have an updated version within the next 1-2 hours from now.

To address points mentioned above, I don't expect the map to be played as much besides the weekends due to player counts, hence being 40v40. It would still be great whenever there's enough of a player count to see how gameplay is affected to see if there's anything else missing. The glass as a kill reward is also a mistake & should be patched with the reference attribute above. Everything else makes sense and should be pushed within the next version.

**Comment by Scripteding** [comment]
Hi @calcastor, here's an updated version that includes those changes above. Let me know if anything else pops up!

Map Download (+includes xml & png): https://drive.google.com/file/d/1RCBu_qsSArGda7xg2DJL-ivCETu10Jjz/view?usp=sharing

**Comment by calcastor** [comment]
Loaded in baeefcf07e53336909cc29017f90e7a5b9a3600d

**Comment by technodono** [comment]
> ### Checklist
> * [x]  I have [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks) the map. (If you used OCC Mapmaker and downloaded your map, it has been pruned for you.)
> * [x]  I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
> * [x]  I have read and understood the  [map submission guidelines](https://oc.tc/docs/submissions).
> * [x]  I have created an XML file.
> * [x]  I have created a map image.
> * [x]  I have uploaded the map zip file to a file sharing service.
> * [x]  The map has been tested locally to make sure it works.
> 
> ### Map Name
> Kingdom
> 
> ### Gamemode & Map Description
> Classic CTW gamemode taking battle out on fields of kingdoms!
> 
> ### Team Sizes
> 2 Teams, 40 Each
> 
> ### Screenshots
> https://imgur.com/a/VmDxuoP
> 
> ### XML
> https://gist.github.com/Scripteding/4f27acc2efb48a190ee10cbde9200521
> 
> ### Map Image
> ![map](https://private-user-images.githubusercontent.com/96262437/341912385-24ccbd8c-180f-43a4-800b-5d88094765e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mzc2NjYsIm5iZiI6MTcxOTgzNzM2NiwicGF0aCI6Ii85NjI2MjQzNy8zNDE5MTIzODUtMjRjY2JkOGMtMTgwZi00M2E0LTgwMGItNWQ4ODA5NDc2NWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEyMzYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYjE4Mjk4YWVkZjQwZTFlN2QwMmNhM2ViZDE1YmRlZWQyMWYxZjRjMTk0NGZhNjE5Njc5NDMxNTJhZDE3NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7xrisXclp1IFw5ibIyhOK03BmbTxY3dnNB-D3t9BH5E)
> 
> ### Map Download
> https://drive.google.com/file/d/1ZIzNHRMLdvSeEf2AYYKFaeqMZLV6lnMC/view?usp=sharing

Looking at the map image here I'm slightly concerned that the amount of anvils in the build may cause some lag. This isn't a big issue by any means but something to consider when working with blocks like fences, gates, anvils... e.c.t.

**Comment by eliminate123** [comment]
Its great seeing new mapmakers. Heres my feedback/opinions on how to improve this map/other maps you make in the future.

1) This map could benefit from larger markers over each wool room. Currently there are flags but they are quite small. Also some flags are harder to see bc of the way they are facing. Making the flags larger and facing east to west should fix this. Also the flags above wool rooms can be destroyed by trolls, maybe making them indestructible would be beneficial. Some maps have symbols above and on the sides of wool rooms.

2) Each spawn could benefit from more red/blue coloring. I can see players being confused which spawn is what due to render distanced and unloaded chunks. More flags could help.

3) Close off unused buildings in the spawns. There are some buildings without any interior (which is perfectly fine) but blocking off the entrances to them with closed doors and blacking out the windows could make them look better.

4) I think the wool monuments could use some details around them maybe a 3x3 pillar or something just so they are a bit more obvious and harder to miss (players are stupid and blind most of the time). Could even just add some colored clay around the base of them.

5) The back pit of each wool room could benefit from being 2-3 blocks deeper (I personally think it would be fine without the bedrock steps in the back pit). Also pink and purple wool rooms are missing a column of buttons (https://i.imgur.com/JBHPH0z.png)

6) I think it could be beneficial for players not to build in the void circle in the middle of the map. This would add some chokepoints on each side of the circle. It would also deter just making a skybridge that is completely flat

7) In the future I personally would avoid having lanes that dont really lead anywhere like this for example (https://i.imgur.com/S43LRw0.jpeg). Although it leads to a bridge, I can see it getting blocked with bridges/stairs/blockspam as the game continues. I personally like to have a zipper approach to my lanes (where one side goes in and the other goes out). This is an example on one of my maps (https://i.imgur.com/nNKJR3X.png). Snow Level by Tkes is a great example of this (https://i.imgur.com/TB32TOk.jpeg). Even just extending a lane 2 blocks out where you want people to bridge from is beneficial 

I think something along the lines of this would be beneficial and lead players to the desired route to the other side (https://i.imgur.com/oY7hE73.jpeg). Where the cross hatch is a section that could be removed (makes it a bit easier for attackers). 

8) I love hoppers/cauldrons/anvils too and I know theres not many block choices in 1.8 but as others mentioned they might lag players. You would be surprised how many players on the server have bad computers.


Other than that this is a very nice map with appealing aesthetics. Its great to see more people making maps. The server thrives off community made maps, and I can see this map being very popular with players as time continues. I find creating a good layout is the hardest part of map making, but practice makes perfect. I look forward to the maps you two will make in the future.

**Comment by eliminate123** [comment]
> Its great seeing new mapmakers. Heres my feedback/opinions on how to improve this map/other maps you make in the future.
> 
> 1. This map could benefit from larger markers over each wool room. Currently there are flags but they are quite small. Also some flags are harder to see bc of the way they are facing. Making the flags larger and facing east to west should fix this. Also the flags above wool rooms can be destroyed by trolls, maybe making them indestructible would be beneficial. Some maps have symbols above and on the sides of wool rooms.
> 2. Each spawn could benefit from more red/blue coloring. I can see players being confused which spawn is what due to render distanced and unloaded chunks. More flags could help.
> 3. Close off unused buildings in the spawns. There are some buildings without any interior (which is perfectly fine) but blocking off the entrances to them with closed doors and blacking out the windows could make them look better.
> 4. I think the wool monuments could use some details around them maybe a 3x3 pillar or something just so they are a bit more obvious and harder to miss (players are stupid and blind most of the time). Could even just add some colored clay around the base of them.
> 5. The back pit of each wool room could benefit from being 2-3 blocks deeper (I personally think it would be fine without the bedrock steps in the back pit). Also pink and purple wool rooms are missing a column of buttons (https://i.imgur.com/JBHPH0z.png)
> 6. I think it could be beneficial for players not to build in the void circle in the middle of the map. This would add some chokepoints on each side of the circle. It would also deter just making a skybridge that is completely flat
> 7. In the future I personally would avoid having lanes that dont really lead anywhere like this for example (https://i.imgur.com/S43LRw0.jpeg). Although it leads to a bridge, I can see it getting blocked with bridges/stairs/blockspam as the game continues. I personally like to have a zipper approach to my lanes (where one side goes in and the other goes out). This is an example on one of my maps (https://i.imgur.com/nNKJR3X.png). Snow Level by Tkes is a great example of this (https://i.imgur.com/TB32TOk.jpeg). Even just extending a lane 2 blocks out where you want people to bridge from is beneficial
> 
> I think something along the lines of this would be beneficial and lead players to the desired route to the other side (https://i.imgur.com/oY7hE73.jpeg). Where the cross hatch is a section that could be removed (makes it a bit easier for attackers).
> 
> 8. I love hoppers/cauldrons/anvils too and I know theres not many block choices in 1.8 but as others mentioned they might lag players. You would be surprised how many players on the server have bad computers.
> 
> Other than that this is a very nice map with appealing aesthetics. Its great to see more people making maps. The server thrives off community made maps, and I can see this map being very popular with players as time continues. I find creating a good layout is the hardest part of map making, but practice makes perfect. I look forward to the maps you two will make in the future.

crazy yap session

**Comment by Scripteding** [comment]
@eliminate123 Thanks for all of the feedback provided! I've gone ahead and pushed the first update that involves points 1-5 (#899 ). Those points seemed the easiest to change so I've gone ahead and made those QOL changes. For points 6-8, I'll eventually want to address them, however I'd like to see how the map plays at a 35v35/40v40 player count first. There might be a need for a rework of mid, especially since the map already feel pretty long with the last game going over an hour with 23v23 player counts. Lastly for point 8 since it's not related to testing the map, I'll want to change those blocks out eventually although it mostly just takes time haha. I appreciate the time spent on giving feedback and hopefully helps the map run a bit better than prior versions.
