### ISSUE TITLE
[CTW/12v12v12v12] Two-Quarter

### ISSUE THREAD

**Issue by Pe241** [OvercastCommunity/CommunityMaps#9]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
~~2/4~~ → Two-Quarter Palace

## Gamemode & Map Description  
Theme: 2(wools/team) / 4wools

Someone might think this is 4team CTW... ,but it's not. This is 2Team CTW (Magenta vs Cyan).
Both team spawns in the central buildings. Magenta teleports to Red side and Pink side, Cyan teleports to Bule side and Light Blue side. Everyone must capture the 2 wools in enemy side (Magenta:Blue and Light Blue, Cyan:Red and Pink) and go back to monument. You can only go to monument area with having any wools and using portal from each base.
The difference between this map and other CTW maps is that the next island is enemy territory.You must defend your wool rooms from enemies coming from two directions.
## Team Sizes
24vs24

## Screenshots
[Imgur v1.1.0](https://imgur.com/a/WglFqRs)
# XML
[Gist](https://gist.github.com/Pe241/b34d52dac1e865b817853a5b421b0f11)

# Map Image
![map](https://user-images.githubusercontent.com/18105767/90677182-efd6eb00-e297-11ea-9c54-e89662117c76.png)

# Download Link
[v1.1.0](https://drive.google.com/file/d/1UB-DGaYJMuD-StLhGXqJgg0FrKMzVkkw/view?usp=sharing)
[v1.1.1](https://drive.google.com/file/d/16f1kiroYC-kbVe1uH1KIpBeoztZg5K6R/view?usp=sharing)

**Comment by Pugzy** [comment]
Thanks for the submission. I've not loaded this locally yet so this feedback is based on the images provided.

The layout and concept look interesting but I do not feel the aesthetics are up to the standard of existing maps on the server. The terrain lacks depth and variation in both height and blocks used. As the map doesn't have a theme and uses almost exclusively quartz and stained clay it looks like something generic that is still waiting for a skin.

If you want to have a go at making the map more stylised then here are some CTW maps with flat terrain and no real theme that you could draw inspiration from `Wit's End`, `Turf Wars`, `Race for Victory` (series in general), `Cyril`, `Fourchette`. Or if you fancied trying to skin the map with a theme inspiration may come from `Outback`, `Cake Day`, `Golden Drought`. Images for these (most of them) and many other maps can be found [here](https://github.com/OvercastCommunity/Maps).

The map name using the longer slash will not work as this goes against the naming conventions and would make it hard for players and staff to find and set the map via in game commands. Please see the docs for further info on [naming conventions](https://pgm.dev/docs/guides/xml-pointers/conventions#naming-conventions). It may be that the map is named using words rather than numeric values, i.e. Two Fourths.

**Comment by Pe241** [comment]
Thank you for your feedback, @Pugzy .

### Updated to v1.1.0

### Terrain

- Renewed. The main blocks are quartz, stained_clay, stained_glass, grass, and floating water.
### Xml

- Adjusted regions and messages. Details are in Gist.

- Renamed map.

### Others

- Changed map.png.

- Edited primary post.

Please check v1.1.0. Thank you.

**Comment by Pugzy** [comment]
Righty, loaded this locally so I could get a clearer look than the image album.

I would remove the middle mess, it's not integral to gameplay, doesn't quite fit the theme of the rest of the map and is stuck in the middle of the map like a sore thumb (so prevents you from viewing both quarters owned by your team). I would reduce the entire structure down to an observer spawn platform like on `Ouroboros`.

This would require moving the wool monuments and team spawns that are currently placed in this area. A good location for these would be the big bedrock slabs (under the wool rooms). The team spawns could be under there (similar size room to the wool rooms but for their own team to spawn in). You would still need a portal to get to the other side but maybe replace the portal to the lane with an actual path. I'll try to get a screenshot of this as its a little hard to explain.

The leaves hanging from the quartz pillars on front line add detail but it doesn't fit with the map, leaves/nature vs all the quartz, clay and glass. I think the `Palace` part of the map name could be played on a little more to influence additional structures and a rework of the wool rooms. Take a look at [this](https://forum.minetest.net/viewtopic.php?t=14241) map (in Minetest not Minecraft) but the design could be used to draw inspiration from.

I think the details on the floor could do with splitting up as its a bit repetitive across the whole map. An example of this would be adding borders and edging like so. The same applies for the quartz across the front of the map, one solid block looks a bit plain 

![image](https://user-images.githubusercontent.com/8608892/92311046-6d466f00-efab-11ea-9903-23ef9c043733.png)

Break up large amounts of blocks with patterns such as these quartz pillars to break up the wool room windows. The image also shows the alternative slab grid above the wool rooms removed, this doesn't look too nice and a better-looking pattern (or none at all) would be better imo.

![image](https://user-images.githubusercontent.com/8608892/92311073-a1ba2b00-efab-11ea-86e5-1666963e6984.png)

I think a few more tweaks to the aesthetics of this map and the removal of the middle structure would bring it to a point where testing can begin. Interested in seeing how the split islands play out as this is a unique layout.

**Comment by fixitqixit** [comment]
@Pugzy @Pe241 Any updates on the status of this map?

**Comment by Pe241** [comment]
Thank you for feedback!
I'll change spawn point structures and designs. Changes are large scale, it may take half-week.

**Comment by fixitqixit** [comment]
@Pe241 No rush! Feel free to create a pull request for this map so that the mapdevs can see it and get it implemented ASAP.

**Comment by Pe241** [comment]
### Updated to v1.1.1

### Changed

- [Design](https://imgur.com/a/BdoNUsu)

- Many Regions

**Comment by fixitqixit** [comment]
I have just added this to the Community Maps repository @Pe241. Hopefully I will have a chance to test it and provide feedback in the coming week.

**Comment by fixitqixit** [comment]
@Pe241 Just played! The match went pretty well though I think I need to test when more players are on to truly see how the game plays. Seems like a fun map though!

**Comment by fixitqixit** [comment]
Oops

**Comment by master00ofdsiware** [comment]
Every time I have seen this map play, the match has lasted only a few minutes; organizing a defense is incredibly difficult. The map divides each team up into two unrelated halves, which means that players from one island rarely go to their team's other island. It also doesn't help that the spawn areas and portals have an unintuitive layout, spawning players randomly at one of the islands instead of having two portals and the player chooses one.

I would very strongly suggest converting this into a 4 team map; that way the layout should be more manageable. You may also add islands to the void gap if you want to improve diagonal mobility.

**Comment by Pugzy** [comment]
What if it remained a two-team map but diagonally? Not seen a map that has gameplay like this before.

**Comment by master00ofdsiware** [comment]
> What if it remained a two-team map but diagonally? Not seen a map that has gameplay like this before.

That is also a valid option; it would remind me of Xion a bit.

**Comment by Pe241** [comment]
If it change to 4 teams map, I think it will lost the characteristic.
Anyway,  I'll narrow the way to the woolroom to one, making easier to defent.

**Comment by master00ofdsiware** [comment]
- Players get too many blocks in the spawnkit, 32 logs and 32 stained glass would probably be enough.
- Lower the build height limit, it's way too high for such a small map.
- Currently the issue is that the players' sides are too close to each other... I suggest making the water gaps larger, and adding a mid island into each water gap that a team bridges to before completing the bridge to the enemy side.

**Comment by calcastor** [comment]
As this map stands now, I think it's pretty close to being ready for rotation. I recommend that punch bows be removed as a wool room gear item; there are very little game modes or situations in which I think they are necessary especially in the current meta. This isn't a "must-do" but I'd highly suggest it, especially given that a couple older maps such as Cargo, where they were featured somewhat heavily in a similar manner (though more impactful gameplay wise), have been updated/redux-ed to have them removed.

One change I would like to see though is larger and more detailed midpoint islands in the void gaps. Compared to when I've seen this map play previously following its semi-recent big update, I think the larger void gaps were a needed improvement. I also think the islands in mid are necessary given the length of the void gaps. Right now though, they don't necessarily serve any other purpose other than a bridging break-point. I would suggest enlarging them and making them more detailed, with any structures, trees, etc. you see fit. They may also maybe benefit from something that encourages players going to them. Perhaps a spawner that gives golden apples or a potion effect such as speed would work well, but whatever you decide for that is up to you.

**Comment by Pe241** [comment]
🏳
